// @generated by scripts/generate-runtime-policy.mjs - DO NOT EDIT.
// Source: src/app/runtime-policy.source.json -> scheduledJobs (hash 6ae34d2d43c2b7bc)
import type {
  JobCatalog,
  JobExecutorKey,
  JobTypeDefinition,
} from "./contracts.ts";

export const JOB_CATALOG: JobCatalog = {
  schemaVersion: 1,
  tasks: [
    {
      id: "exchange.refresh",
      executorKey: "refresh-exchange-v1",
      category: "collection",
      defaultSchedule: {
        kind: "interval",
        minutes: 1440,
      },
      constraints: {
        minMinutes: 60,
        maxMinutes: 10080,
        singleFlight: true,
      },
      startupPolicy: "if-stale",
      retry: {
        maxAttempts: 2,
        backoffSeconds: [300, 900],
      },
      timeoutMs: 15000,
      queue: "background",
      network: "allowed",
      requiresApproval: false,
      ui: {
        settingsVisible: true,
        i18nKey: "tasks.usageRefresh",
      },
    },
    {
      id: "usage.refresh",
      executorKey: "refresh-usage-v1",
      category: "collection",
      defaultSchedule: {
        kind: "interval",
        minutes: 5,
      },
      constraints: {
        minMinutes: 1,
        maxMinutes: 1440,
        singleFlight: true,
      },
      startupPolicy: "if-stale",
      retry: {
        maxAttempts: 2,
        backoffSeconds: [30, 120],
      },
      timeoutMs: 120000,
      queue: "background",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: true,
        i18nKey: "tasks.usageRefresh",
      },
    },
    {
      id: "skills.refresh",
      executorKey: "refresh-skills-v1",
      category: "collection",
      defaultSchedule: {
        kind: "interval",
        minutes: 60,
      },
      constraints: {
        minMinutes: 15,
        maxMinutes: 10080,
        singleFlight: true,
      },
      startupPolicy: "if-stale",
      retry: {
        maxAttempts: 2,
        backoffSeconds: [60, 300],
      },
      timeoutMs: 180000,
      queue: "background",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: true,
        i18nKey: "tasks.skillsRefresh",
      },
    },
    {
      id: "sessions.refresh",
      executorKey: "refresh-sessions-v1",
      category: "collection",
      defaultSchedule: {
        kind: "interval",
        minutes: 30,
      },
      constraints: {
        minMinutes: 5,
        maxMinutes: 1440,
        singleFlight: true,
      },
      startupPolicy: "if-stale",
      retry: {
        maxAttempts: 1,
        backoffSeconds: [60],
      },
      timeoutMs: 180000,
      queue: "background",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: true,
        i18nKey: "tasks.sessionsRefresh",
      },
    },
    {
      id: "installation.refresh",
      executorKey: "refresh-installation-v1",
      category: "collection",
      defaultSchedule: {
        kind: "interval",
        minutes: 360,
      },
      constraints: {
        minMinutes: 60,
        maxMinutes: 10080,
        singleFlight: true,
      },
      startupPolicy: "if-stale",
      retry: {
        maxAttempts: 1,
        backoffSeconds: [120],
      },
      timeoutMs: 60000,
      queue: "background",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: true,
        i18nKey: "tasks.installationsRefresh",
      },
    },
    {
      id: "retention.apply",
      executorKey: "apply-retention-v1",
      category: "maintenance",
      defaultSchedule: {
        kind: "daily",
        localTime: "03:00",
      },
      constraints: {
        minMinutes: 1440,
        maxMinutes: 10080,
        singleFlight: true,
      },
      startupPolicy: "disabled",
      retry: {
        maxAttempts: 1,
        backoffSeconds: [300],
      },
      timeoutMs: 120000,
      queue: "maintenance",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: true,
        i18nKey: "tasks.retentionApply",
      },
    },
    {
      id: "backup.daily",
      executorKey: "backup-daily-v1",
      category: "maintenance",
      defaultSchedule: {
        kind: "interval",
        minutes: 1440,
      },
      constraints: {
        minMinutes: 1440,
        maxMinutes: 10080,
        singleFlight: true,
      },
      startupPolicy: "disabled",
      retry: {
        maxAttempts: 1,
        backoffSeconds: [300],
      },
      timeoutMs: 120000,
      queue: "maintenance",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: true,
        i18nKey: "tasks.backupDaily",
      },
    },
    {
      id: "reports.generate",
      executorKey: "generate-report-v1",
      category: "report",
      defaultSchedule: {
        kind: "weekly",
        localTime: "18:00",
        weekday: 5,
      },
      constraints: {
        minMinutes: 10080,
        maxMinutes: 10080,
        singleFlight: true,
      },
      startupPolicy: "disabled",
      retry: {
        maxAttempts: 2,
        backoffSeconds: [120, 600],
      },
      timeoutMs: 300000,
      queue: "interactive",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: false,
        i18nKey: "tasks.reportsGenerate",
      },
    },
    {
      id: "reports.generate.daily",
      executorKey: "generate-report-v1",
      category: "report",
      defaultSchedule: {
        kind: "daily",
        localTime: "18:00",
      },
      constraints: {
        minMinutes: 1440,
        maxMinutes: 1440,
        singleFlight: true,
      },
      startupPolicy: "disabled",
      retry: {
        maxAttempts: 2,
        backoffSeconds: [120, 600],
      },
      timeoutMs: 300000,
      queue: "interactive",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: false,
        i18nKey: "tasks.reportsGenerate",
      },
    },
    {
      id: "reports.generate.weekly",
      executorKey: "generate-report-v1",
      category: "report",
      defaultSchedule: {
        kind: "weekly",
        localTime: "18:00",
        weekday: 5,
      },
      constraints: {
        minMinutes: 10080,
        maxMinutes: 10080,
        singleFlight: true,
      },
      startupPolicy: "disabled",
      retry: {
        maxAttempts: 2,
        backoffSeconds: [120, 600],
      },
      timeoutMs: 300000,
      queue: "interactive",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: false,
        i18nKey: "tasks.reportsGenerate",
      },
    },
    {
      id: "reports.generate.monthly",
      executorKey: "generate-report-v1",
      category: "report",
      defaultSchedule: {
        kind: "monthly",
        localTime: "18:00",
        dayOfMonth: 31,
      },
      constraints: {
        minMinutes: 1440,
        maxMinutes: 10080,
        singleFlight: true,
      },
      startupPolicy: "disabled",
      retry: {
        maxAttempts: 2,
        backoffSeconds: [120, 600],
      },
      timeoutMs: 300000,
      queue: "interactive",
      network: "forbidden",
      requiresApproval: false,
      ui: {
        settingsVisible: false,
        i18nKey: "tasks.reportsGenerate",
      },
    },
  ],
};
export const JOB_DEFINITIONS: readonly JobTypeDefinition[] = JOB_CATALOG.tasks;
export const JOB_EXECUTOR_KEYS: readonly JobExecutorKey[] = [
  "refresh-exchange-v1",
  "refresh-usage-v1",
  "refresh-skills-v1",
  "refresh-sessions-v1",
  "refresh-installation-v1",
  "apply-retention-v1",
  "backup-daily-v1",
  "generate-report-v1",
];
export const JOB_CATALOG_VERSION = "6ae34d2d43c2b7bc";

/** Explicit registry skeleton. P3-04 supplies implementations; no dynamic import is permitted. */
export const JOB_EXECUTOR_REGISTRY: Readonly<Record<JobExecutorKey, null>> =
  Object.freeze(
    Object.fromEntries(JOB_EXECUTOR_KEYS.map((key) => [key, null])) as Record<
      JobExecutorKey,
      null
    >,
  );
