# Keep npm dependencies up to date with automated pull requests.
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    groups:
      tanstack:
        patterns:
          - "@tanstack/*"
      radix:
        patterns:
          - "@radix-ui/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
