import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "build",
      "release",
      "test-results",
      "vendor",
      // Documentation directory (contains external zip unpack samples), not
      // repository code.
      "docs",
      "src/lib/tool-registry/public-manifest.generated.ts", // generated by generate:manifest
      "src/lib/tool-registry/definitions.generated.ts", // generated by generate:tool-imports
      "src/lib/pricing/pricing-definitions.generated.ts", // generated by generate:pricing-imports
      "src/lib/security/security-rules.generated.ts", // generated by generate:security-rules
      "src/modules/tasks/definitions/job-catalog.generated.ts", // generated by generate:job-imports
      "src/routeTree.gen.ts", // generated by the TanStack Router plugin
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    files: ["src/components/ui/**/*.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  {
    files: ["src/lib/theme.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  // Repository tooling (verify/inspect/generate scripts). Previously unlinted:
  // the `**/*.{ts,tsx}` glob above does not match `.mts`/`.mjs`, so the database
  // gate scripts were never checked (review finding P2-14). Node globals, no
  // React rules, and prettier formatting is applied by the shared config below.
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["scripts/**/*.{mts,mjs,cjs,js}", "*.config.js", "*.config.mjs"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  eslintPluginPrettier,
);
