// @generated by scripts/generate-pricing-imports.mjs - DO NOT EDIT.
import type { PricingManifest, PricingPack } from "./contracts.ts";
import type {
  BillingRoute,
  FallbackProfile,
  ModelAliasRule,
  ModelCatalogEntry,
  RatePack,
  RouteSelectionRule,
} from "./contracts.ts";

export const PRICING_MANIFEST: PricingManifest = {
  "schemaVersion": 1,
  "packs": [
    {
      "packId": "defaults",
      "path": "src/lib/pricing/rules/defaults.rules.json"
    },
    {
      "packId": "openai",
      "path": "src/lib/pricing/rules/openai.rules.json"
    },
    {
      "packId": "anthropic",
      "path": "src/lib/pricing/rules/anthropic.rules.json"
    },
    {
      "packId": "google",
      "path": "src/lib/pricing/rules/google.rules.json"
    },
    {
      "packId": "china-providers",
      "path": "src/lib/pricing/rules/china-providers.rules.json"
    },
    {
      "packId": "tool-routing",
      "path": "src/lib/pricing/rules/tool-routing.rules.json"
    }
  ],
  "modelCatalog": {
    "path": "src/lib/pricing/rules/model-catalog.json"
  },
  "billingRoutes": {
    "path": "src/lib/pricing/rules/billing-routes.json"
  },
  "modelAliasRules": {
    "path": "src/lib/pricing/rules/model-alias-rules.json"
  },
  "routeSelectionRules": {
    "path": "src/lib/pricing/rules/route-selection-rules.json"
  },
  "ratePacks": [
    {
      "packId": "official-routes",
      "path": "src/lib/pricing/rules/rate-packs/official.routes.json"
    }
  ],
  "fallbackProfiles": {
    "path": "src/lib/pricing/rules/fallback-profiles.json"
  }
};

export const PRICING_PACKS: readonly PricingPack[] = [
  {
    "schemaVersion": 1,
    "packId": "defaults",
    "revision": "2026-08-06",
    "rules": [],
    "rates": [],
    "fallbackProfiles": [
      {
        "id": "api-generic-v1",
        "appliesTo": "api-metered",
        "usdNanoPerMillion": {
          "input": "1000000000",
          "output": "3000000000",
          "cacheRead": "100000000",
          "cacheWrite": "1250000000"
        },
        "confidence": "estimated",
        "label": "通用 API 估算费率；非官方账单",
        "reviewRequired": true
      },
      {
        "id": "subscription-zero-marginal-v1",
        "appliesTo": "subscription",
        "confidence": "not-billable",
        "label": "订阅制用量，不按 API 单价估算"
      },
      {
        "id": "unpriced-v1",
        "appliesTo": "unknown",
        "confidence": "unpriced",
        "label": "未配置费率，等待运营补充"
      }
    ]
  },
  {
    "schemaVersion": 1,
    "packId": "openai",
    "revision": "2026-08-06",
    "rules": [
      {
        "id": "openai-gpt-5.6-sol-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "gpt-5.6-sol"
        },
        "convertTo": "gpt-5.6-sol",
        "rateRef": "openai/gpt-5.6-sol/2026-07-27"
      },
      {
        "id": "openai-gpt-5.6-sol-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "gpt-5.6-sol"
        },
        "convertTo": "gpt-5.6-sol",
        "rateRef": "openai/gpt-5.6-sol/2026-07-27"
      },
      {
        "id": "openai-gpt-5.6-terra-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "gpt-5.6-terra"
        },
        "convertTo": "gpt-5.6-terra",
        "rateRef": "openai/gpt-5.6-terra/2026-07-27"
      },
      {
        "id": "openai-gpt-5.6-terra-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "gpt-5.6-terra"
        },
        "convertTo": "gpt-5.6-terra",
        "rateRef": "openai/gpt-5.6-terra/2026-07-27"
      },
      {
        "id": "openai-gpt-5.6-luna-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "gpt-5.6-luna"
        },
        "convertTo": "gpt-5.6-luna",
        "rateRef": "openai/gpt-5.6-luna/2026-07-27"
      },
      {
        "id": "openai-gpt-5.6-luna-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "gpt-5.6-luna"
        },
        "convertTo": "gpt-5.6-luna",
        "rateRef": "openai/gpt-5.6-luna/2026-07-27"
      },
      {
        "id": "openai-gpt-5.5-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "gpt-5.5"
        },
        "convertTo": "gpt-5.5",
        "rateRef": "openai/gpt-5.5/2026-07-27"
      },
      {
        "id": "openai-gpt-5.5-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "gpt-5.5"
        },
        "convertTo": "gpt-5.5",
        "rateRef": "openai/gpt-5.5/2026-07-27"
      },
      {
        "id": "openai-gpt-5.4-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "gpt-5.4"
        },
        "convertTo": "gpt-5.4",
        "rateRef": "openai/gpt-5.4/2026-07-27"
      },
      {
        "id": "openai-gpt-5.4-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "gpt-5.4"
        },
        "convertTo": "gpt-5.4",
        "rateRef": "openai/gpt-5.4/2026-07-27"
      },
      {
        "id": "openai-gpt-5.2-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "gpt-5.2"
        },
        "convertTo": "gpt-5.2",
        "rateRef": "openai/gpt-5.2/2026-07-27"
      },
      {
        "id": "openai-gpt-5.2-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "gpt-5.2"
        },
        "convertTo": "gpt-5.2",
        "rateRef": "openai/gpt-5.2/2026-07-27"
      },
      {
        "id": "openai-gpt-5.1-codex-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "gpt-5.1-codex"
        },
        "convertTo": "gpt-5.1-codex",
        "rateRef": "openai/gpt-5.1-codex/2026-07-27"
      },
      {
        "id": "openai-gpt-5.1-codex-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "gpt-5.1-codex"
        },
        "convertTo": "gpt-5.1-codex",
        "rateRef": "openai/gpt-5.1-codex/2026-07-27"
      },
      {
        "id": "openai-gpt-5-codex-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "gpt-5-codex"
        },
        "convertTo": "gpt-5-codex",
        "rateRef": "openai/gpt-5-codex/2026-07-27"
      },
      {
        "id": "openai-gpt-5-codex-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "gpt-5-codex"
        },
        "convertTo": "gpt-5-codex",
        "rateRef": "openai/gpt-5-codex/2026-07-27"
      }
    ],
    "rates": [
      {
        "id": "openai/gpt-5.6-sol/2026-07-27",
        "canonicalModelId": "gpt-5.6-sol",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "5000000000",
          "output": "30000000000",
          "cacheRead": "500000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.6-terra/2026-07-27",
        "canonicalModelId": "gpt-5.6-terra",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "2500000000",
          "output": "15000000000",
          "cacheRead": "250000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.6-luna/2026-07-27",
        "canonicalModelId": "gpt-5.6-luna",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1000000000",
          "output": "6000000000",
          "cacheRead": "100000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.5/2026-07-27",
        "canonicalModelId": "gpt-5.5",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "6250000000",
          "output": "37500000000",
          "cacheRead": "625000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.4/2026-07-27",
        "canonicalModelId": "gpt-5.4",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "2500000000",
          "output": "15000000000",
          "cacheRead": "250000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.2/2026-07-27",
        "canonicalModelId": "gpt-5.2",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1750000000",
          "output": "14000000000",
          "cacheRead": "175000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.1-codex/2026-07-27",
        "canonicalModelId": "gpt-5.1-codex",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1250000000",
          "output": "10000000000",
          "cacheRead": "125000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5-codex/2026-07-27",
        "canonicalModelId": "gpt-5-codex",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1250000000",
          "output": "10000000000",
          "cacheRead": "125000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      }
    ]
  },
  {
    "schemaVersion": 1,
    "packId": "anthropic",
    "revision": "2026-08-06",
    "rules": [
      {
        "id": "anthropic-claude-opus-4-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "claude-opus-4"
        },
        "convertTo": "claude-opus-4",
        "rateRef": "anthropic/claude-opus-4/2026-07-27"
      },
      {
        "id": "anthropic-claude-opus-4-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "claude-opus-4"
        },
        "convertTo": "claude-opus-4",
        "rateRef": "anthropic/claude-opus-4/2026-07-27"
      },
      {
        "id": "anthropic-claude-sonnet-4-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "claude-sonnet-4"
        },
        "convertTo": "claude-sonnet-4",
        "rateRef": "anthropic/claude-sonnet-4/2026-07-27"
      },
      {
        "id": "anthropic-claude-sonnet-4-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "claude-sonnet-4"
        },
        "convertTo": "claude-sonnet-4",
        "rateRef": "anthropic/claude-sonnet-4/2026-07-27"
      },
      {
        "id": "anthropic-claude-3-7-sonnet-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "claude-3-7-sonnet"
        },
        "convertTo": "claude-3-7-sonnet",
        "rateRef": "anthropic/claude-3-7-sonnet/2026-07-27"
      },
      {
        "id": "anthropic-claude-3-7-sonnet-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "claude-3-7-sonnet"
        },
        "convertTo": "claude-3-7-sonnet",
        "rateRef": "anthropic/claude-3-7-sonnet/2026-07-27"
      },
      {
        "id": "anthropic-claude-3-5-haiku-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "claude-3-5-haiku"
        },
        "convertTo": "claude-3-5-haiku",
        "rateRef": "anthropic/claude-3-5-haiku/2026-07-27"
      },
      {
        "id": "anthropic-claude-3-5-haiku-prefix",
        "scope": {},
        "priority": 120,
        "when": {
          "kind": "prefix",
          "value": "claude-3-5-haiku"
        },
        "convertTo": "claude-3-5-haiku",
        "rateRef": "anthropic/claude-3-5-haiku/2026-07-27"
      }
    ],
    "rates": [
      {
        "id": "anthropic/claude-opus-4/2026-07-27",
        "canonicalModelId": "claude-opus-4",
        "billingRouteId": "official-anthropic",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "15000000000",
          "output": "75000000000",
          "cacheRead": "1500000000",
          "cacheWrite": "18750000000"
        },
        "source": {
          "kind": "official",
          "label": "Anthropic API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "anthropic/claude-sonnet-4/2026-07-27",
        "canonicalModelId": "claude-sonnet-4",
        "billingRouteId": "official-anthropic",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "3000000000",
          "output": "15000000000",
          "cacheRead": "300000000",
          "cacheWrite": "3750000000"
        },
        "source": {
          "kind": "official",
          "label": "Anthropic API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "anthropic/claude-3-7-sonnet/2026-07-27",
        "canonicalModelId": "claude-3-7-sonnet",
        "billingRouteId": "official-anthropic",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "3000000000",
          "output": "15000000000",
          "cacheRead": "300000000",
          "cacheWrite": "3750000000"
        },
        "source": {
          "kind": "official",
          "label": "Anthropic API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "anthropic/claude-3-5-haiku/2026-07-27",
        "canonicalModelId": "claude-3-5-haiku",
        "billingRouteId": "official-anthropic",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "800000000",
          "output": "4000000000",
          "cacheRead": "80000000",
          "cacheWrite": "1000000000"
        },
        "source": {
          "kind": "official",
          "label": "Anthropic API pricing",
          "verifiedAt": "2026-07-27"
        }
      }
    ]
  },
  {
    "schemaVersion": 1,
    "packId": "google",
    "revision": "2026-08-06",
    "rules": [],
    "rates": []
  },
  {
    "schemaVersion": 1,
    "packId": "china-providers",
    "revision": "2026-08-06",
    "rules": [
      {
        "id": "deepseek-v4-pro-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "deepseek-v4-pro"
        },
        "convertTo": "deepseek-v4-pro",
        "rateRef": "deepseek/deepseek-v4-pro/2026-07-27"
      },
      {
        "id": "minimax-m2-5-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "minimax-m2-5"
        },
        "convertTo": "minimax-m2-5",
        "rateRef": "minimax/minimax-m2-5/2026-07-27"
      },
      {
        "id": "minimax-m2-7-highspeed-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "minimax-m2-7-highspeed"
        },
        "convertTo": "minimax-m2-7-highspeed",
        "rateRef": "minimax/minimax-m2-7-highspeed/2026-07-27"
      },
      {
        "id": "glm-5-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "glm-5"
        },
        "convertTo": "glm-5",
        "rateRef": "zhipu/glm-5/2026-07-27"
      },
      {
        "id": "doubao-seed-2-0-code-exact",
        "scope": {},
        "priority": 200,
        "when": {
          "kind": "exact",
          "value": "doubao-seed-2-0-code"
        },
        "convertTo": "doubao-seed-2-0-code",
        "rateRef": "volcengine/doubao-seed-2-0-code/2026-07-27"
      }
    ],
    "rates": [
      {
        "id": "deepseek/deepseek-v4-pro/2026-07-27",
        "canonicalModelId": "deepseek-v4-pro",
        "billingRouteId": "official-deepseek",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "435000000",
          "output": "870000000",
          "cacheRead": "3625000",
          "cacheWrite": "0"
        },
        "source": {
          "kind": "official",
          "label": "DeepSeek 官方定价",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "minimax/minimax-m2-5/2026-07-27",
        "canonicalModelId": "minimax-m2-5",
        "billingRouteId": "official-minimax",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "300000000",
          "output": "1200000000",
          "cacheRead": "30000000",
          "cacheWrite": "375000000"
        },
        "source": {
          "kind": "official",
          "label": "MiniMax 官方定价",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "minimax/minimax-m2-7-highspeed/2026-07-27",
        "canonicalModelId": "minimax-m2-7-highspeed",
        "billingRouteId": "official-minimax",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "600000000",
          "output": "2400000000",
          "cacheRead": "60000000",
          "cacheWrite": "375000000"
        },
        "source": {
          "kind": "official",
          "label": "MiniMax 官方定价",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "zhipu/glm-5/2026-07-27",
        "canonicalModelId": "glm-5",
        "billingRouteId": "official-zhipu",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1000000000",
          "output": "3200000000",
          "cacheRead": "200000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "community",
          "label": "LiteLLM · GLM-5",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "volcengine/doubao-seed-2-0-code/2026-07-27",
        "canonicalModelId": "doubao-seed-2-0-code",
        "billingRouteId": "official-volcengine",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1333333333",
          "output": "6666666667",
          "cacheRead": "266666667",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "火山引擎官方阶梯定价（CNY→USD@7.2）",
          "verifiedAt": "2026-07-27"
        },
        "tiers": [
          {
            "maxInputTokens": 32000,
            "rates": {
              "input": "444444444",
              "output": "2222222222",
              "cacheRead": "88888889"
            }
          },
          {
            "maxInputTokens": 128000,
            "rates": {
              "input": "666666667",
              "output": "3333333333",
              "cacheRead": "133333333"
            }
          },
          {
            "maxInputTokens": null,
            "rates": {
              "input": "1333333333",
              "output": "6666666667",
              "cacheRead": "266666667"
            }
          }
        ]
      }
    ]
  },
  {
    "schemaVersion": 1,
    "packId": "tool-routing",
    "revision": "2026-08-06",
    "rules": [],
    "rates": []
  }
];

export const PRICING_MODEL_CATALOG: readonly ModelCatalogEntry[] = [
  {
    "id": "claude-3-5-haiku",
    "provider": "anthropic",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "claude-3-7-sonnet",
    "provider": "anthropic",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "claude-opus-4",
    "provider": "anthropic",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "claude-sonnet-4",
    "provider": "anthropic",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "deepseek-v4-pro",
    "provider": "deepseek",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "doubao-seed-2-0-code",
    "provider": "volcengine",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "glm-5",
    "provider": "zhipu",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "gpt-5-codex",
    "provider": "openai",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "gpt-5.1-codex",
    "provider": "openai",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "gpt-5.2",
    "provider": "openai",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "gpt-5.4",
    "provider": "openai",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "gpt-5.5",
    "provider": "openai",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "gpt-5.6-luna",
    "provider": "openai",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "gpt-5.6-sol",
    "provider": "openai",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "gpt-5.6-terra",
    "provider": "openai",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "minimax-m2-5",
    "provider": "minimax",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  },
  {
    "id": "minimax-m2-7-highspeed",
    "provider": "minimax",
    "aliases": {
      "profile": "generic-normalize-v1"
    }
  }
];

export const PRICING_BILLING_ROUTES: readonly BillingRoute[] = [
  {
    "id": "official-openai",
    "name": "openai official API",
    "kind": "official-api",
    "provider": "openai",
    "endpointEvidence": [
      "endpoint",
      "baseUrl"
    ],
    "region": {
      "default": "global"
    },
    "status": "active",
    "reference": true
  },
  {
    "id": "official-anthropic",
    "name": "anthropic official API",
    "kind": "official-api",
    "provider": "anthropic",
    "endpointEvidence": [
      "endpoint",
      "baseUrl"
    ],
    "region": {
      "default": "global"
    },
    "status": "active",
    "reference": true
  },
  {
    "id": "official-google",
    "name": "google official API",
    "kind": "official-api",
    "provider": "google",
    "endpointEvidence": [
      "endpoint",
      "baseUrl"
    ],
    "region": {
      "default": "global"
    },
    "status": "active",
    "reference": true
  },
  {
    "id": "official-deepseek",
    "name": "deepseek official API",
    "kind": "official-api",
    "provider": "deepseek",
    "endpointEvidence": [
      "endpoint",
      "baseUrl"
    ],
    "region": {
      "default": "global"
    },
    "status": "active",
    "reference": true
  },
  {
    "id": "official-minimax",
    "name": "minimax official API",
    "kind": "official-api",
    "provider": "minimax",
    "endpointEvidence": [
      "endpoint",
      "baseUrl"
    ],
    "region": {
      "default": "global"
    },
    "status": "active",
    "reference": true
  },
  {
    "id": "official-zhipu",
    "name": "zhipu official API",
    "kind": "official-api",
    "provider": "zhipu",
    "endpointEvidence": [
      "endpoint",
      "baseUrl"
    ],
    "region": {
      "default": "global"
    },
    "status": "active",
    "reference": true
  },
  {
    "id": "official-volcengine",
    "name": "volcengine official API",
    "kind": "official-api",
    "provider": "volcengine",
    "endpointEvidence": [
      "endpoint",
      "baseUrl"
    ],
    "region": {
      "default": "global"
    },
    "status": "active",
    "reference": true
  }
];

export const PRICING_MODEL_ALIAS_RULES: readonly ModelAliasRule[] = [
  {
    "id": "openai-gpt-5.6-sol-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "gpt-5.6-sol"
    },
    "convertTo": "gpt-5.6-sol",
    "rateRef": "openai/gpt-5.6-sol/2026-07-27"
  },
  {
    "id": "openai-gpt-5.6-sol-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "gpt-5.6-sol"
    },
    "convertTo": "gpt-5.6-sol",
    "rateRef": "openai/gpt-5.6-sol/2026-07-27"
  },
  {
    "id": "openai-gpt-5.6-terra-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "gpt-5.6-terra"
    },
    "convertTo": "gpt-5.6-terra",
    "rateRef": "openai/gpt-5.6-terra/2026-07-27"
  },
  {
    "id": "openai-gpt-5.6-terra-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "gpt-5.6-terra"
    },
    "convertTo": "gpt-5.6-terra",
    "rateRef": "openai/gpt-5.6-terra/2026-07-27"
  },
  {
    "id": "openai-gpt-5.6-luna-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "gpt-5.6-luna"
    },
    "convertTo": "gpt-5.6-luna",
    "rateRef": "openai/gpt-5.6-luna/2026-07-27"
  },
  {
    "id": "openai-gpt-5.6-luna-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "gpt-5.6-luna"
    },
    "convertTo": "gpt-5.6-luna",
    "rateRef": "openai/gpt-5.6-luna/2026-07-27"
  },
  {
    "id": "openai-gpt-5.5-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "gpt-5.5"
    },
    "convertTo": "gpt-5.5",
    "rateRef": "openai/gpt-5.5/2026-07-27"
  },
  {
    "id": "openai-gpt-5.5-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "gpt-5.5"
    },
    "convertTo": "gpt-5.5",
    "rateRef": "openai/gpt-5.5/2026-07-27"
  },
  {
    "id": "openai-gpt-5.4-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "gpt-5.4"
    },
    "convertTo": "gpt-5.4",
    "rateRef": "openai/gpt-5.4/2026-07-27"
  },
  {
    "id": "openai-gpt-5.4-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "gpt-5.4"
    },
    "convertTo": "gpt-5.4",
    "rateRef": "openai/gpt-5.4/2026-07-27"
  },
  {
    "id": "openai-gpt-5.2-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "gpt-5.2"
    },
    "convertTo": "gpt-5.2",
    "rateRef": "openai/gpt-5.2/2026-07-27"
  },
  {
    "id": "openai-gpt-5.2-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "gpt-5.2"
    },
    "convertTo": "gpt-5.2",
    "rateRef": "openai/gpt-5.2/2026-07-27"
  },
  {
    "id": "openai-gpt-5.1-codex-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "gpt-5.1-codex"
    },
    "convertTo": "gpt-5.1-codex",
    "rateRef": "openai/gpt-5.1-codex/2026-07-27"
  },
  {
    "id": "openai-gpt-5.1-codex-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "gpt-5.1-codex"
    },
    "convertTo": "gpt-5.1-codex",
    "rateRef": "openai/gpt-5.1-codex/2026-07-27"
  },
  {
    "id": "openai-gpt-5-codex-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "gpt-5-codex"
    },
    "convertTo": "gpt-5-codex",
    "rateRef": "openai/gpt-5-codex/2026-07-27"
  },
  {
    "id": "openai-gpt-5-codex-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "gpt-5-codex"
    },
    "convertTo": "gpt-5-codex",
    "rateRef": "openai/gpt-5-codex/2026-07-27"
  },
  {
    "id": "anthropic-claude-opus-4-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "claude-opus-4"
    },
    "convertTo": "claude-opus-4",
    "rateRef": "anthropic/claude-opus-4/2026-07-27"
  },
  {
    "id": "anthropic-claude-opus-4-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "claude-opus-4"
    },
    "convertTo": "claude-opus-4",
    "rateRef": "anthropic/claude-opus-4/2026-07-27"
  },
  {
    "id": "anthropic-claude-sonnet-4-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "claude-sonnet-4"
    },
    "convertTo": "claude-sonnet-4",
    "rateRef": "anthropic/claude-sonnet-4/2026-07-27"
  },
  {
    "id": "anthropic-claude-sonnet-4-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "claude-sonnet-4"
    },
    "convertTo": "claude-sonnet-4",
    "rateRef": "anthropic/claude-sonnet-4/2026-07-27"
  },
  {
    "id": "anthropic-claude-3-7-sonnet-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "claude-3-7-sonnet"
    },
    "convertTo": "claude-3-7-sonnet",
    "rateRef": "anthropic/claude-3-7-sonnet/2026-07-27"
  },
  {
    "id": "anthropic-claude-3-7-sonnet-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "claude-3-7-sonnet"
    },
    "convertTo": "claude-3-7-sonnet",
    "rateRef": "anthropic/claude-3-7-sonnet/2026-07-27"
  },
  {
    "id": "anthropic-claude-3-5-haiku-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "claude-3-5-haiku"
    },
    "convertTo": "claude-3-5-haiku",
    "rateRef": "anthropic/claude-3-5-haiku/2026-07-27"
  },
  {
    "id": "anthropic-claude-3-5-haiku-prefix",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 120,
    "when": {
      "kind": "prefix",
      "value": "claude-3-5-haiku"
    },
    "convertTo": "claude-3-5-haiku",
    "rateRef": "anthropic/claude-3-5-haiku/2026-07-27"
  },
  {
    "id": "deepseek-v4-pro-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "deepseek-v4-pro"
    },
    "convertTo": "deepseek-v4-pro",
    "rateRef": "deepseek/deepseek-v4-pro/2026-07-27"
  },
  {
    "id": "minimax-m2-5-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "minimax-m2-5"
    },
    "convertTo": "minimax-m2-5",
    "rateRef": "minimax/minimax-m2-5/2026-07-27"
  },
  {
    "id": "minimax-m2-7-highspeed-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "minimax-m2-7-highspeed"
    },
    "convertTo": "minimax-m2-7-highspeed",
    "rateRef": "minimax/minimax-m2-7-highspeed/2026-07-27"
  },
  {
    "id": "glm-5-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "glm-5"
    },
    "convertTo": "glm-5",
    "rateRef": "zhipu/glm-5/2026-07-27"
  },
  {
    "id": "doubao-seed-2-0-code-exact",
    "scope": {
      "billingRouteIds": []
    },
    "priority": 200,
    "when": {
      "kind": "exact",
      "value": "doubao-seed-2-0-code"
    },
    "convertTo": "doubao-seed-2-0-code",
    "rateRef": "volcengine/doubao-seed-2-0-code/2026-07-27"
  }
];

export const PRICING_ROUTE_SELECTION_RULES: readonly RouteSelectionRule[] = [];

export const PRICING_RATE_PACKS: readonly RatePack[] = [
  {
    "schemaVersion": 1,
    "packId": "official-routes",
    "revision": "2026-08-06",
    "rates": [
      {
        "id": "openai/gpt-5.6-sol/2026-07-27",
        "canonicalModelId": "gpt-5.6-sol",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "5000000000",
          "output": "30000000000",
          "cacheRead": "500000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.6-terra/2026-07-27",
        "canonicalModelId": "gpt-5.6-terra",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "2500000000",
          "output": "15000000000",
          "cacheRead": "250000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.6-luna/2026-07-27",
        "canonicalModelId": "gpt-5.6-luna",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1000000000",
          "output": "6000000000",
          "cacheRead": "100000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.5/2026-07-27",
        "canonicalModelId": "gpt-5.5",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "6250000000",
          "output": "37500000000",
          "cacheRead": "625000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.4/2026-07-27",
        "canonicalModelId": "gpt-5.4",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "2500000000",
          "output": "15000000000",
          "cacheRead": "250000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.2/2026-07-27",
        "canonicalModelId": "gpt-5.2",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1750000000",
          "output": "14000000000",
          "cacheRead": "175000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5.1-codex/2026-07-27",
        "canonicalModelId": "gpt-5.1-codex",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1250000000",
          "output": "10000000000",
          "cacheRead": "125000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "openai/gpt-5-codex/2026-07-27",
        "canonicalModelId": "gpt-5-codex",
        "billingRouteId": "official-openai",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1250000000",
          "output": "10000000000",
          "cacheRead": "125000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "OpenAI API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "anthropic/claude-opus-4/2026-07-27",
        "canonicalModelId": "claude-opus-4",
        "billingRouteId": "official-anthropic",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "15000000000",
          "output": "75000000000",
          "cacheRead": "1500000000",
          "cacheWrite": "18750000000"
        },
        "source": {
          "kind": "official",
          "label": "Anthropic API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "anthropic/claude-sonnet-4/2026-07-27",
        "canonicalModelId": "claude-sonnet-4",
        "billingRouteId": "official-anthropic",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "3000000000",
          "output": "15000000000",
          "cacheRead": "300000000",
          "cacheWrite": "3750000000"
        },
        "source": {
          "kind": "official",
          "label": "Anthropic API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "anthropic/claude-3-7-sonnet/2026-07-27",
        "canonicalModelId": "claude-3-7-sonnet",
        "billingRouteId": "official-anthropic",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "3000000000",
          "output": "15000000000",
          "cacheRead": "300000000",
          "cacheWrite": "3750000000"
        },
        "source": {
          "kind": "official",
          "label": "Anthropic API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "anthropic/claude-3-5-haiku/2026-07-27",
        "canonicalModelId": "claude-3-5-haiku",
        "billingRouteId": "official-anthropic",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "800000000",
          "output": "4000000000",
          "cacheRead": "80000000",
          "cacheWrite": "1000000000"
        },
        "source": {
          "kind": "official",
          "label": "Anthropic API pricing",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "deepseek/deepseek-v4-pro/2026-07-27",
        "canonicalModelId": "deepseek-v4-pro",
        "billingRouteId": "official-deepseek",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "435000000",
          "output": "870000000",
          "cacheRead": "3625000",
          "cacheWrite": "0"
        },
        "source": {
          "kind": "official",
          "label": "DeepSeek 官方定价",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "minimax/minimax-m2-5/2026-07-27",
        "canonicalModelId": "minimax-m2-5",
        "billingRouteId": "official-minimax",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "300000000",
          "output": "1200000000",
          "cacheRead": "30000000",
          "cacheWrite": "375000000"
        },
        "source": {
          "kind": "official",
          "label": "MiniMax 官方定价",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "minimax/minimax-m2-7-highspeed/2026-07-27",
        "canonicalModelId": "minimax-m2-7-highspeed",
        "billingRouteId": "official-minimax",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "600000000",
          "output": "2400000000",
          "cacheRead": "60000000",
          "cacheWrite": "375000000"
        },
        "source": {
          "kind": "official",
          "label": "MiniMax 官方定价",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "zhipu/glm-5/2026-07-27",
        "canonicalModelId": "glm-5",
        "billingRouteId": "official-zhipu",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1000000000",
          "output": "3200000000",
          "cacheRead": "200000000",
          "cacheWrite": null
        },
        "source": {
          "kind": "community",
          "label": "LiteLLM · GLM-5",
          "verifiedAt": "2026-07-27"
        }
      },
      {
        "id": "volcengine/doubao-seed-2-0-code/2026-07-27",
        "canonicalModelId": "doubao-seed-2-0-code",
        "billingRouteId": "official-volcengine",
        "region": "global",
        "effective": {
          "from": "2026-07-27",
          "to": null
        },
        "usdNanoPerMillion": {
          "input": "1333333333",
          "output": "6666666667",
          "cacheRead": "266666667",
          "cacheWrite": null
        },
        "source": {
          "kind": "official",
          "label": "火山引擎官方阶梯定价（CNY→USD@7.2）",
          "verifiedAt": "2026-07-27"
        },
        "tiers": [
          {
            "maxInputTokens": 32000,
            "rates": {
              "input": "444444444",
              "output": "2222222222",
              "cacheRead": "88888889"
            }
          },
          {
            "maxInputTokens": 128000,
            "rates": {
              "input": "666666667",
              "output": "3333333333",
              "cacheRead": "133333333"
            }
          },
          {
            "maxInputTokens": null,
            "rates": {
              "input": "1333333333",
              "output": "6666666667",
              "cacheRead": "266666667"
            }
          }
        ]
      }
    ]
  }
];

export const PRICING_FALLBACK_PROFILES: readonly FallbackProfile[] = [
  {
    "id": "api-generic-v1",
    "appliesTo": "api-metered",
    "usdNanoPerMillion": {
      "input": "1000000000",
      "output": "3000000000",
      "cacheRead": "100000000",
      "cacheWrite": "1250000000"
    },
    "confidence": "estimated",
    "label": "通用 API 估算费率；非官方账单",
    "reviewRequired": true
  },
  {
    "id": "subscription-zero-marginal-v1",
    "appliesTo": "subscription",
    "confidence": "not-billable",
    "label": "订阅制用量，不按 API 单价估算"
  },
  {
    "id": "unpriced-v1",
    "appliesTo": "unknown",
    "confidence": "unpriced",
    "label": "未配置费率，等待运营补充"
  }
];

export const PRICING_REGISTRY_VERSION: string = "804d653df875fa2b";
