// @generated by scripts/generate-runtime-policy.mjs - DO NOT EDIT.
// Source: src/app/runtime-policy.source.json (hash 6935a620012d50fd)

import type {
  RuntimePolicySource,
  SnapshotPolicyKey,
} from "./runtime-policy.schema.ts";

export const RUNTIME_POLICY_SOURCE_HASH = "6935a620012d50fd";

/** Full runtime policy. Server-only: contains executors, timeouts and network permission. */
export const RUNTIME_POLICY: RuntimePolicySource = {
  schemaVersion: 1,
  snapshotPolicies: {
    exchangeRates: {
      freshForMinutes: 1440,
      defaultRefreshMinutes: 1440,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
      timeoutMs: 15000,
      network: "allowed",
    },
    usage: {
      freshForMinutes: 15,
      defaultRefreshMinutes: 15,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
      timeoutMs: 120000,
      network: "forbidden",
    },
    sessions: {
      freshForMinutes: 30,
      defaultRefreshMinutes: 30,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
      timeoutMs: 180000,
      network: "forbidden",
    },
    skills: {
      freshForMinutes: 60,
      defaultRefreshMinutes: 60,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
      timeoutMs: 180000,
      network: "forbidden",
    },
    toolInstallations: {
      freshForMinutes: 360,
      defaultRefreshMinutes: 360,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
      timeoutMs: 60000,
      network: "forbidden",
    },
    wslTopology: {
      freshForMinutes: 360,
      defaultRefreshMinutes: 360,
      startupPolicy: "on-demand-if-stale",
      staleReadable: true,
      manualRefresh: true,
      timeoutMs: 30000,
      network: "forbidden",
    },
    skillMarketEvidence: {
      freshForMinutes: 360,
      defaultRefreshMinutes: 360,
      startupPolicy: "on-demand-if-stale",
      staleReadable: true,
      manualRefresh: true,
      timeoutMs: 30000,
      network: "allowed",
    },
  },
  scheduledJobs: {
    schemaVersion: 1,
    tasks: [
      {
        id: "exchange.refresh",
        executorKey: "refresh-exchange-v1",
        category: "collection",
        defaultSchedule: {
          kind: "interval",
          minutes: 1440,
        },
        constraints: {
          minMinutes: 60,
          maxMinutes: 10080,
          singleFlight: true,
        },
        startupPolicy: "if-stale",
        retry: {
          maxAttempts: 2,
          backoffSeconds: [300, 900],
        },
        timeoutMs: 15000,
        queue: "background",
        network: "allowed",
        requiresApproval: false,
        ui: {
          settingsVisible: true,
          i18nKey: "tasks.usageRefresh",
        },
      },
      {
        id: "usage.refresh",
        executorKey: "refresh-usage-v1",
        category: "collection",
        defaultSchedule: {
          kind: "interval",
          minutes: 15,
        },
        constraints: {
          minMinutes: 5,
          maxMinutes: 1440,
          singleFlight: true,
        },
        startupPolicy: "if-stale",
        retry: {
          maxAttempts: 2,
          backoffSeconds: [30, 120],
        },
        timeoutMs: 120000,
        queue: "background",
        network: "forbidden",
        requiresApproval: false,
        ui: {
          settingsVisible: true,
          i18nKey: "tasks.usageRefresh",
        },
      },
      {
        id: "skills.refresh",
        executorKey: "refresh-skills-v1",
        category: "collection",
        defaultSchedule: {
          kind: "interval",
          minutes: 60,
        },
        constraints: {
          minMinutes: 15,
          maxMinutes: 10080,
          singleFlight: true,
        },
        startupPolicy: "if-stale",
        retry: {
          maxAttempts: 2,
          backoffSeconds: [60, 300],
        },
        timeoutMs: 180000,
        queue: "background",
        network: "forbidden",
        requiresApproval: false,
        ui: {
          settingsVisible: true,
          i18nKey: "tasks.skillsRefresh",
        },
      },
      {
        id: "sessions.refresh",
        executorKey: "refresh-sessions-v1",
        category: "collection",
        defaultSchedule: {
          kind: "interval",
          minutes: 30,
        },
        constraints: {
          minMinutes: 5,
          maxMinutes: 1440,
          singleFlight: true,
        },
        startupPolicy: "if-stale",
        retry: {
          maxAttempts: 1,
          backoffSeconds: [60],
        },
        timeoutMs: 180000,
        queue: "background",
        network: "forbidden",
        requiresApproval: false,
        ui: {
          settingsVisible: true,
          i18nKey: "tasks.sessionsRefresh",
        },
      },
      {
        id: "installation.refresh",
        executorKey: "refresh-installation-v1",
        category: "collection",
        defaultSchedule: {
          kind: "interval",
          minutes: 360,
        },
        constraints: {
          minMinutes: 60,
          maxMinutes: 10080,
          singleFlight: true,
        },
        startupPolicy: "if-stale",
        retry: {
          maxAttempts: 1,
          backoffSeconds: [120],
        },
        timeoutMs: 60000,
        queue: "background",
        network: "forbidden",
        requiresApproval: false,
        ui: {
          settingsVisible: true,
          i18nKey: "tasks.installationsRefresh",
        },
      },
      {
        id: "retention.apply",
        executorKey: "apply-retention-v1",
        category: "maintenance",
        defaultSchedule: {
          kind: "daily",
          localTime: "03:00",
        },
        constraints: {
          minMinutes: 1440,
          maxMinutes: 10080,
          singleFlight: true,
        },
        startupPolicy: "disabled",
        retry: {
          maxAttempts: 1,
          backoffSeconds: [300],
        },
        timeoutMs: 120000,
        queue: "maintenance",
        network: "forbidden",
        requiresApproval: false,
        ui: {
          settingsVisible: true,
          i18nKey: "tasks.retentionApply",
        },
      },
      {
        id: "reports.generate",
        executorKey: "generate-report-v1",
        category: "report",
        defaultSchedule: {
          kind: "weekly",
          localTime: "09:00",
          weekday: 1,
        },
        constraints: {
          minMinutes: 10080,
          maxMinutes: 10080,
          singleFlight: true,
        },
        startupPolicy: "disabled",
        retry: {
          maxAttempts: 2,
          backoffSeconds: [120, 600],
        },
        timeoutMs: 300000,
        queue: "interactive",
        network: "forbidden",
        requiresApproval: false,
        ui: {
          settingsVisible: false,
          i18nKey: "tasks.reportsGenerate",
        },
      },
    ],
  },
  resourceBudgets: {
    maxHeavyCollectors: 1,
    maxFileOperations: 16,
    maxProjectClassifiers: 8,
  },
  rollout: {
    defaultStage: "new-default",
  },
};

/** Renderer-safe projection. Never contains executor keys, URLs, paths, commands or network permission. */
export const RENDERER_SAFE_RUNTIME_POLICY: RendererSafeRuntimePolicy = {
  schemaVersion: 1,
  snapshotPolicies: {
    exchangeRates: {
      freshForMinutes: 1440,
      defaultRefreshMinutes: 1440,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
    },
    usage: {
      freshForMinutes: 15,
      defaultRefreshMinutes: 15,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
    },
    sessions: {
      freshForMinutes: 30,
      defaultRefreshMinutes: 30,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
    },
    skills: {
      freshForMinutes: 60,
      defaultRefreshMinutes: 60,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
    },
    toolInstallations: {
      freshForMinutes: 360,
      defaultRefreshMinutes: 360,
      startupPolicy: "if-stale",
      staleReadable: true,
      manualRefresh: true,
    },
    wslTopology: {
      freshForMinutes: 360,
      defaultRefreshMinutes: 360,
      startupPolicy: "on-demand-if-stale",
      staleReadable: true,
      manualRefresh: true,
    },
    skillMarketEvidence: {
      freshForMinutes: 360,
      defaultRefreshMinutes: 360,
      startupPolicy: "on-demand-if-stale",
      staleReadable: true,
      manualRefresh: true,
    },
  },
  resourceBudgets: {
    maxHeavyCollectors: 1,
    maxFileOperations: 16,
    maxProjectClassifiers: 8,
  },
  rollout: {
    defaultStage: "new-default",
  },
};

export interface RendererSafeSnapshotPolicy {
  readonly freshForMinutes: number;
  readonly defaultRefreshMinutes: number;
  readonly startupPolicy: "disabled" | "if-stale" | "on-demand-if-stale";
  readonly staleReadable: boolean;
  readonly manualRefresh: boolean;
}

export interface RendererSafeRuntimePolicy {
  readonly schemaVersion: 1;
  readonly snapshotPolicies: Record<
    SnapshotPolicyKey,
    RendererSafeSnapshotPolicy
  >;
  readonly resourceBudgets: {
    readonly maxHeavyCollectors: number;
    readonly maxFileOperations: number;
    readonly maxProjectClassifiers: number;
  };
  readonly rollout: {
    readonly defaultStage:
      | "legacy"
      | "shadow"
      | "compact-read-model"
      | "snapshot-read"
      | "unified-refresh"
      | "new-default";
  };
}

const FORBIDDEN_SERIALIZED_TOKENS = [
  "executor",
  "url",
  "command",
  "path",
  "network",
  "timeoutMs",
  "retry",
] as const;

export function rendererPolicyIsSafe(
  policy: RendererSafeRuntimePolicy,
): boolean {
  const serialized = JSON.stringify(policy).toLowerCase();
  return FORBIDDEN_SERIALIZED_TOKENS.every(
    (token) => !serialized.includes(token),
  );
}
