// @generated by scripts/generate-tool-imports.mjs - DO NOT EDIT.
import type { RawToolDefinition, SharedPolicyPacks } from "./schema.ts";

export const RAW_TOOL_DEFINITIONS: readonly RawToolDefinition[] = [
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "claude-code",
    "display": {
      "name": "Claude Code",
      "nameZh": "Claude Code"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".claude"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Claude"
        }
      ],
      "executable": {
        "shared": [
          "claude"
        ]
      }
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".claude/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "claude-rollout-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".claude/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "context": {
        "mode": "native",
        "reader": "claude-context-v1",
        "dimensions": [
          "tools",
          "skills",
          "commands",
          "mcp",
          "toolOutputs"
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "resume",
        "reader": "claude-session-v1",
        "command": [
          "claude",
          "--resume",
          "{sessionId}"
        ]
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "codex",
    "display": {
      "name": "Codex CLI",
      "nameZh": "Codex CLI"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".codex"
        }
      ],
      "executable": {
        "shared": [
          "codex"
        ]
      }
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".codex/skills"
          }
        ],
        "envHome": "CODEX_HOME",
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "codex-rollout-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".codex/sessions",
            "glob": "**/rollout-*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".codex/archived_sessions",
            "glob": "**/rollout-*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "context": {
        "mode": "native",
        "reader": "codex-context-v1",
        "dimensions": [
          "tools",
          "skills",
          "commands",
          "mcp",
          "toolOutputs"
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "resume",
        "reader": "codex-session-v1",
        "command": [
          "codex",
          "resume",
          "{sessionId}"
        ]
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model",
      "evidence": {
        "endpointField": "endpoint"
      }
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "cursor",
    "display": {
      "name": "Cursor",
      "nameZh": "Cursor"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Cursor"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".cursor"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".cursor/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "Cursor/User/globalStorage",
            "glob": "**/*usage*.json",
            "format": "json"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "Cursor/User/globalStorage",
            "glob": "**/*usage*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".cursor",
            "glob": "**/*usage*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "kiro",
    "display": {
      "name": "Kiro",
      "nameZh": "Kiro"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".kiro"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "gemini-cli",
    "display": {
      "name": "Gemini CLI",
      "nameZh": "Gemini CLI"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".gemini"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".gemini/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".gemini/tmp",
            "glob": "**/chats/*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".gemini",
            "glob": "**/*usage*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "opencode",
    "display": {
      "name": "OpenCode",
      "nameZh": "OpenCode"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "configHome",
          "path": "opencode"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "opencode"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".config/opencode/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "dataHome",
            "path": "opencode/storage/message",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".opencode",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "openclaw",
    "display": {
      "name": "OpenClaw",
      "nameZh": "OpenClaw"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".openclaw"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".openclaw/workspace/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "every-code",
    "display": {
      "name": "Every Code",
      "nameZh": "Every Code"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".every-code"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "hermes",
    "display": {
      "name": "Hermes Agent",
      "nameZh": "Hermes Agent"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".hermes"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".hermes/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "github-copilot",
    "display": {
      "name": "GitHub Copilot",
      "nameZh": "GitHub Copilot"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "configHome",
          "path": "github-copilot"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "configHome",
            "path": "github-copilot",
            "glob": "**/*usage*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "github-copilot",
            "glob": "**/*usage*.json",
            "format": "json"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "github-copilot",
            "glob": "**/*usage*.json",
            "format": "json"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "kimi-code",
    "display": {
      "name": "Kimi Code",
      "nameZh": "Kimi Code"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".kimi"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".kimi/sessions",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".kimi/logs",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "omp",
    "display": {
      "name": "oh-my-pi",
      "nameZh": "oh-my-pi"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".omp"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".oh-my-pi"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "codebuddy",
    "display": {
      "name": "CodeBuddy",
      "nameZh": "CodeBuddy"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".codebuddy"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "workbuddy",
    "display": {
      "name": "WorkBuddy",
      "nameZh": "WorkBuddy"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".workbuddy"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "workbuddy-native",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".workbuddy/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "grok",
    "display": {
      "name": "Grok Build",
      "nameZh": "Grok Build"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".grok"
        }
      ],
      "executable": {
        "shared": [
          "grok"
        ]
      }
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".grok/skills"
          }
        ],
        "envHome": "GROK_HOME",
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".grok/sessions",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".grok/logs",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "resume",
        "reader": "grok-session-v1",
        "command": [
          "grok",
          "--resume",
          "{sessionId}"
        ]
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "kilo-cli",
    "display": {
      "name": "Kilo CLI",
      "nameZh": "Kilo CLI"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".kilo"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "kilo"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "kilocode",
    "display": {
      "name": "Kilo Code",
      "nameZh": "Kilo Code"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Code/User/globalStorage/kilocode.kilo-code"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "antigravity",
    "display": {
      "name": "Antigravity",
      "nameZh": "Antigravity"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".gemini/antigravity"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Antigravity"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".gemini/antigravity/skills"
          },
          {
            "base": "home",
            "path": ".gemini/antigravity-ide/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "pi",
    "display": {
      "name": "pi",
      "nameZh": "pi"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".pi"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "craft",
    "display": {
      "name": "Craft Agents",
      "nameZh": "Craft Agents"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".craft-agent"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "roo-code",
    "display": {
      "name": "Roo Code",
      "nameZh": "Roo Code"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Code/User/globalStorage/rooveterinaryinc.roo-cline"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "Code/User/globalStorage/rooveterinaryinc.roo-cline/tasks",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "configHome",
            "path": "Code/User/globalStorage/rooveterinaryinc.roo-cline/tasks",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "Code/User/globalStorage/rooveterinaryinc.roo-cline/tasks",
            "glob": "**/*.json",
            "format": "json"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "zed",
    "display": {
      "name": "Zed Agent",
      "nameZh": "Zed Agent"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Zed"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "zed"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "goose",
    "display": {
      "name": "Goose",
      "nameZh": "Goose"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "goose"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".goose"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "droid",
    "display": {
      "name": "Droid",
      "nameZh": "Droid"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".factory"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "mimo",
    "display": {
      "name": "Mimo Code",
      "nameZh": "Mimo Code"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "mimocode"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "zcode",
    "display": {
      "name": "ZCode",
      "nameZh": "ZCode"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".zcode"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "anythingllm",
    "display": {
      "name": "AnythingLLM Desktop",
      "nameZh": "AnythingLLM Desktop"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "anythingllm-desktop"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "aipy",
    "display": {
      "name": "AiPy",
      "nameZh": "AiPy"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "aipy-pro"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "aipy-pro"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-sqlite",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "aipy-pro",
            "glob": "aipy",
            "format": "sqlite"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "aipy-pro",
            "glob": "aipy",
            "format": "sqlite"
          }
        ],
        "mapping": {
          "timestamp": [
            "timestamp"
          ],
          "sessionId": [
            "sessionId"
          ],
          "model": [
            "model"
          ],
          "project": [
            "project"
          ],
          "inputTokens": [
            "inputTokens"
          ],
          "outputTokens": [
            "outputTokens"
          ],
          "reasoningOutputTokens": [
            "reasoningOutputTokens"
          ],
          "totalTokens": [
            "totalTokens"
          ]
        },
        "maxFileSizeBytes": 536870912,
        "query": "SELECT\n  e.time AS timestamp,\n  e.task_id AS sessionId,\n  COALESCE(NULLIF(e.model, ''), NULLIF(t.model, ''), 'unknown') AS model,\n  COALESCE(NULLIF(t.workdir, ''), 'unknown') AS project,\n  CAST(COALESCE(json_extract(e.usage, '$.input_tokens'), 0) AS INTEGER) AS inputTokens,\n  CAST(COALESCE(json_extract(e.usage, '$.output_tokens'), 0) AS INTEGER) AS outputTokens,\n  CAST(COALESCE(json_extract(e.usage, '$.reasoning_tokens'), 0) AS INTEGER) AS reasoningOutputTokens,\n  CAST(COALESCE(json_extract(e.usage, '$.total_tokens'), 0) AS INTEGER) AS totalTokens\nFROM task_event e\nLEFT JOIN task t ON t.id = e.task_id\nWHERE e.usage IS NOT NULL AND e.usage <> ''"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "cline",
    "display": {
      "name": "Cline",
      "nameZh": "Cline"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Code/User/globalStorage/saoudrizwan.claude-dev"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "configHome",
          "path": "Code/User/globalStorage/saoudrizwan.claude-dev"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "Code/User/globalStorage/saoudrizwan.claude-dev"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-json",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "Code/User/globalStorage/saoudrizwan.claude-dev/tasks",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "configHome",
            "path": "Code/User/globalStorage/saoudrizwan.claude-dev/tasks",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "Code/User/globalStorage/saoudrizwan.claude-dev/tasks",
            "glob": "**/*.json",
            "format": "json"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  }
];

export const SHARED_POLICY_PACKS: SharedPolicyPacks = {
  "platformProfiles": {
    "schemaVersion": 1,
    "description": "Per-platform path bases and availability defaults (docs §6.1). Resolution priority: shared default < platform group < platform target < tool definition.",
    "targets": [
      "macos",
      "windows10",
      "windows11",
      "linux"
    ],
    "groups": {
      "windows": [
        "windows10",
        "windows11"
      ]
    },
    "basePlatforms": {
      "home": [
        "macos",
        "windows10",
        "windows11",
        "linux"
      ],
      "userProfile": [
        "windows10",
        "windows11"
      ],
      "appData": [
        "macos"
      ],
      "appDataRoaming": [
        "windows10",
        "windows11"
      ],
      "configHome": [
        "macos",
        "linux"
      ],
      "dataHome": [
        "macos",
        "linux"
      ]
    },
    "xdgFallback": {
      "configHome": "~/.config",
      "dataHome": "~/.local/share"
    },
    "defaultStatus": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    }
  },
  "genericReaderDefaults": {
    "schemaVersion": 1,
    "description": "Default field candidates + size cap for generic readers (moved from COMMON_MAPPING / GENERIC_ADAPTER_MAX_FILE_SIZE_BYTES in local-usage/adapters/catalog.ts).",
    "defaultMapping": {
      "records": [
        "events",
        "messages",
        "turns",
        "history",
        "items",
        "data.events",
        "data.messages"
      ],
      "timestamp": [
        "timestamp",
        "created_at",
        "createdAt",
        "time",
        "metadata.timestamp",
        "usage.timestamp"
      ],
      "sessionId": [
        "session_id",
        "sessionId",
        "conversation_id",
        "conversationId",
        "thread_id",
        "threadId",
        "message.session_id",
        "message.sessionId",
        "metadata.session_id",
        "metadata.sessionId"
      ],
      "model": [
        "model",
        "model_id",
        "modelId",
        "metadata.model",
        "usage.model"
      ],
      "project": [
        "cwd",
        "project",
        "project_path",
        "projectPath",
        "workspace",
        "workspace_path",
        "metadata.cwd"
      ],
      "inputTokens": [
        "usage.input_tokens",
        "usage.inputTokens",
        "token_usage.input_tokens",
        "tokenUsage.inputTokens",
        "tokens.input",
        "metrics.input_tokens"
      ],
      "cachedInputTokens": [
        "usage.cached_input_tokens",
        "usage.cache_read_input_tokens",
        "usage.cachedInputTokens",
        "token_usage.cached_input_tokens",
        "tokenUsage.cachedInputTokens",
        "tokens.cached_input"
      ],
      "cacheCreationInputTokens": [
        "usage.cache_creation_input_tokens",
        "usage.cacheCreationInputTokens",
        "token_usage.cache_creation_input_tokens",
        "tokens.cache_creation_input"
      ],
      "outputTokens": [
        "usage.output_tokens",
        "usage.outputTokens",
        "token_usage.output_tokens",
        "tokenUsage.outputTokens",
        "tokens.output",
        "metrics.output_tokens"
      ],
      "reasoningOutputTokens": [
        "usage.reasoning_output_tokens",
        "usage.reasoningOutputTokens",
        "token_usage.reasoning_output_tokens",
        "tokens.reasoning"
      ],
      "totalTokens": [
        "usage.total_tokens",
        "usage.totalTokens",
        "token_usage.total_tokens",
        "tokenUsage.totalTokens",
        "tokens.total",
        "metrics.total_tokens"
      ]
    },
    "defaultMaxFileSizeBytes": 8388608
  },
  "scannerPolicy": {
    "schemaVersion": 1,
    "description": "Scanner budgets and cache naming policy (moved from local-usage/scanner.server.ts constants). Execution (walking, I/O, cache versioning) stays in TypeScript.",
    "lookbackDays": 3650,
    "maxFilesPerSource": 1200,
    "maxDiscoveredEntriesPerSource": 30000,
    "maxJsonlLineLength": 16777216,
    "futureTimestampToleranceMs": 86400000,
    "cacheFileName": "local-usage-index-v10.json",
    "cacheNote": "The implementation cache version (PERSISTENT_CACHE_VERSION) and the registry fingerprint stay in TypeScript; changing either invalidates the persistent cache."
  },
  "skillMarketPolicy": {
    "schemaVersion": 1,
    "description": "Skill-agent UI order, default discovery settings and market install conditions (moved from SKILL_AGENT_ORDER / DEFAULT_MARKERS in local-skills/agent-rules.ts).",
    "skillAgentOrder": [
      "claude-code",
      "codex",
      "cursor",
      "gemini-cli",
      "opencode",
      "grok",
      "hermes",
      "openclaw",
      "antigravity"
    ],
    "defaultMarkers": [
      "SKILL.md",
      "skill.md"
    ],
    "defaultMaxDepth": 3,
    "marketInstallCondition": {
      "requires": [
        "skills.mode=read-write",
        "storage.skills.rootSpecs"
      ],
      "note": "A tool without skill roots must not auto-become a market install target (docs §6)."
    }
  },
  "usageTaxonomy": {
    "schemaVersion": 1,
    "description": "Behavior classification hints and context dimensions (moved from DEBUG_COMMAND_HINTS in local-usage/behavior-classify.ts). Display labels live in the i18n dictionaries.",
    "debugCommandHints": [
      "diff",
      "grep",
      "log",
      "status",
      "test",
      "lint"
    ],
    "behaviorPriority": [
      "debug-command",
      "execution",
      "browser",
      "agent",
      "planning",
      "text-qa"
    ],
    "contextDimensions": {
      "tools": {
        "i18nKey": "dashboard.context.dimTool"
      },
      "skills": {
        "i18nKey": "dashboard.context.dimSkill"
      },
      "commands": {
        "i18nKey": "dashboard.context.dimMessages"
      },
      "mcp": {
        "i18nKey": "dashboard.context.dimMcp"
      },
      "toolOutputs": {
        "i18nKey": "dashboard.context.dimTool"
      }
    }
  },
  "definitionsManifest": {
    "schemaVersion": 1,
    "description": "Explicit, ordered list of built-in tool definitions (docs §5: fixed import list, no runtime directory scanning). Order matches the frozen baseline UI order; aipy/cline are legacy sources (catalogVisible=false).",
    "tools": [
      {
        "id": "claude-code",
        "path": "claude-code.tool.json"
      },
      {
        "id": "codex",
        "path": "codex.tool.json"
      },
      {
        "id": "cursor",
        "path": "cursor.tool.json"
      },
      {
        "id": "kiro",
        "path": "kiro.tool.json"
      },
      {
        "id": "gemini-cli",
        "path": "gemini-cli.tool.json"
      },
      {
        "id": "opencode",
        "path": "opencode.tool.json"
      },
      {
        "id": "openclaw",
        "path": "openclaw.tool.json"
      },
      {
        "id": "every-code",
        "path": "every-code.tool.json"
      },
      {
        "id": "hermes",
        "path": "hermes.tool.json"
      },
      {
        "id": "github-copilot",
        "path": "github-copilot.tool.json"
      },
      {
        "id": "kimi-code",
        "path": "kimi-code.tool.json"
      },
      {
        "id": "omp",
        "path": "omp.tool.json"
      },
      {
        "id": "codebuddy",
        "path": "codebuddy.tool.json"
      },
      {
        "id": "workbuddy",
        "path": "workbuddy.tool.json"
      },
      {
        "id": "grok",
        "path": "grok.tool.json"
      },
      {
        "id": "kilo-cli",
        "path": "kilo-cli.tool.json"
      },
      {
        "id": "kilocode",
        "path": "kilocode.tool.json"
      },
      {
        "id": "antigravity",
        "path": "antigravity.tool.json"
      },
      {
        "id": "pi",
        "path": "pi.tool.json"
      },
      {
        "id": "craft",
        "path": "craft.tool.json"
      },
      {
        "id": "roo-code",
        "path": "roo-code.tool.json"
      },
      {
        "id": "zed",
        "path": "zed.tool.json"
      },
      {
        "id": "goose",
        "path": "goose.tool.json"
      },
      {
        "id": "droid",
        "path": "droid.tool.json"
      },
      {
        "id": "mimo",
        "path": "mimo.tool.json"
      },
      {
        "id": "zcode",
        "path": "zcode.tool.json"
      },
      {
        "id": "anythingllm",
        "path": "anythingllm.tool.json"
      },
      {
        "id": "aipy",
        "path": "aipy.tool.json"
      },
      {
        "id": "cline",
        "path": "cline.tool.json"
      }
    ]
  }
};

export const TOOL_REGISTRY_VERSION: string = "d35f6170e0174ab0";
