// @generated by scripts/generate-tool-imports.mjs - DO NOT EDIT.
import type { RawToolDefinition, SharedPolicyPacks } from "./schema.ts";

export const RAW_TOOL_DEFINITIONS: readonly RawToolDefinition[] = [
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "claude-code",
    "display": {
      "name": "Claude Code",
      "nameZh": "Claude Code",
      "icon": "claude",
      "color": "#d97757"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".claude"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Claude"
        }
      ],
      "executable": {
        "shared": [
          "claude"
        ]
      }
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".claude/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "claude-rollout-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".claude/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "context": {
        "mode": "native",
        "reader": "claude-context-v1",
        "dimensions": [
          "tools",
          "skills",
          "commands",
          "mcp",
          "toolOutputs"
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "resume",
        "reader": "claude-session-v1",
        "command": [
          "claude",
          "--resume",
          "{sessionId}"
        ]
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "codex",
    "display": {
      "name": "Codex",
      "nameZh": "Codex",
      "icon": "other",
      "color": "#10a37f"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".codex"
        }
      ],
      "executable": {
        "shared": [
          "codex"
        ]
      }
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".codex/skills"
          }
        ],
        "envHome": "CODEX_HOME",
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "codex-rollout-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".codex/sessions",
            "glob": "**/rollout-*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".codex/archived_sessions",
            "glob": "**/rollout-*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "context": {
        "mode": "native",
        "reader": "codex-context-v1",
        "dimensions": [
          "tools",
          "skills",
          "commands",
          "mcp",
          "toolOutputs"
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "resume",
        "reader": "codex-session-v1",
        "command": [
          "codex",
          "resume",
          "{sessionId}"
        ]
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model",
      "evidence": {
        "endpointField": "endpoint"
      }
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "cursor",
    "display": {
      "name": "Cursor",
      "nameZh": "Cursor",
      "icon": "cursor",
      "color": "#cfcfcf"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Cursor"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".cursor"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "configHome",
          "path": "tokscale/cursor-cache"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "Cursor"
        }
      ],
      "executable": {
        "shared": [
          "cursor"
        ]
      }
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".cursor/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "Cursor/User/globalStorage",
            "glob": "**/*usage*.json",
            "format": "json"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "Cursor/User/globalStorage",
            "glob": "**/*usage*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".cursor",
            "glob": "**/*usage*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "configHome",
            "path": "tokscale/cursor-cache",
            "glob": "**/*.json",
            "format": "json"
          }
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "kiro",
    "display": {
      "name": "Kiro",
      "nameZh": "Kiro",
      "icon": "other",
      "color": "#01a4ff"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".kiro"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Kiro/User/globalStorage/kiro.kiroagent"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "Kiro/User/globalStorage/kiro.kiroagent"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "configHome",
          "path": "Kiro/User/globalStorage/kiro.kiroagent"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "kiro-cli"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "dataHome",
          "path": "kiro-cli"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "gemini-cli",
    "display": {
      "name": "Gemini CLI",
      "nameZh": "Gemini CLI",
      "icon": "other",
      "color": "#4285f4"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".gemini/tmp"
        }
      ],
      "executable": {
        "shared": [
          "gemini"
        ]
      }
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".gemini/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "gemini-session-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".gemini/tmp",
            "glob": "**/chats/session-*.json",
            "format": "json"
          }
        ],
        "maxFileSizeBytes": 67108864
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "opencode",
    "display": {
      "name": "OpenCode",
      "nameZh": "OpenCode",
      "icon": "other",
      "color": "#f59e0b"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "configHome",
          "path": "opencode"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "opencode"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "opencode/storage/message"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".config/opencode/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "dataHome",
            "path": "opencode/storage/message",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".opencode",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "openclaw",
    "display": {
      "name": "OpenClaw",
      "nameZh": "OpenClaw",
      "icon": "other",
      "color": "#ff5543"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".openclaw"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".openclaw/agents"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".openclaw/workspace/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "openclaw-session-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".openclaw/agents",
            "glob": "*/sessions/**/*.jsonl*",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".openclaw/agents",
            "glob": "*/session-sqlite-import-archive/**/*.jsonl*",
            "format": "jsonl"
          }
        ],
        "maxFileSizeBytes": 67108864
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "every-code",
    "display": {
      "name": "Every Code",
      "nameZh": "Every Code",
      "icon": "other",
      "color": "#00c2a8"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".every-code"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "hermes",
    "display": {
      "name": "Hermes Agent",
      "nameZh": "Hermes Agent",
      "icon": "other",
      "color": "#a78bfa"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".hermes"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".hermes/state.db"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".hermes/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "github-copilot",
    "display": {
      "name": "GitHub Copilot",
      "nameZh": "GitHub Copilot",
      "icon": "other",
      "color": "#6e7681"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "configHome",
          "path": "github-copilot"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "home",
          "path": ".copilot"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "userProfile",
          "path": "Code/User/workspaceStorage"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Code/User/workspaceStorage"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "configHome",
          "path": "Code/User/workspaceStorage"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "configHome",
            "path": "github-copilot",
            "glob": "**/*usage*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "github-copilot",
            "glob": "**/*usage*.json",
            "format": "json"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "github-copilot",
            "glob": "**/*usage*.json",
            "format": "json"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "kimi-code",
    "display": {
      "name": "Kimi Code",
      "nameZh": "Kimi Code",
      "icon": "kimi",
      "color": "#7c5cff"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".kimi"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".kimi-code"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".kimi/sessions",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".kimi/logs",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".kimi-code/sessions",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "omp",
    "display": {
      "name": "oh-my-pi",
      "nameZh": "oh-my-pi",
      "icon": "other",
      "color": "#00b3ff"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".omp"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".oh-my-pi"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".omp/agent/sessions"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".oh-my-pi/agent/sessions"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "codebuddy",
    "display": {
      "name": "CodeBuddy",
      "nameZh": "CodeBuddy",
      "icon": "other",
      "color": "#0052d9"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".codebuddy"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "CodeBuddyExtension/Logs"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "userProfile",
          "path": "Local/CodeBuddyExtension/Logs"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "dataHome",
          "path": "CodeBuddyExtension/Logs"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "workbuddy",
    "display": {
      "name": "WorkBuddy",
      "nameZh": "WorkBuddy",
      "icon": "other",
      "color": "#22d3ee"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".workbuddy"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "workbuddy-native",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".workbuddy/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model",
      "tokenSemantics": {
        "reasoningIncludedInOutput": false
      }
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "grok",
    "display": {
      "name": "Grok Build",
      "nameZh": "Grok Build",
      "icon": "other",
      "color": "#d1d5db"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".grok"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".grok/sessions"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".grok/logs"
        }
      ],
      "executable": {
        "shared": [
          "grok"
        ]
      }
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".grok/skills"
          }
        ],
        "envHome": "GROK_HOME",
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "grok-turn-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".grok/sessions",
            "glob": "**/updates.jsonl",
            "format": "jsonl"
          }
        ],
        "maxFileSizeBytes": 67108864
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "resume",
        "reader": "grok-session-v1",
        "command": [
          "grok",
          "--resume",
          "{sessionId}"
        ]
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "kilo-cli",
    "display": {
      "name": "Kilo CLI",
      "nameZh": "Kilo CLI",
      "icon": "other",
      "color": "#eab308"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".kilo"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "kilo"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "userProfile",
          "path": "Local/kilo"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "kilocode",
    "display": {
      "name": "Kilo Code",
      "nameZh": "Kilo Code",
      "icon": "other",
      "color": "#eab308"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Code/User/globalStorage/kilocode.kilo-code"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "Code/User/globalStorage/kilocode.kilo-code"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "configHome",
          "path": "Code/User/globalStorage/kilocode.kilo-code"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "home",
          "path": ".vscode-server/data/User/globalStorage/kilocode.kilo-code"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "antigravity",
    "display": {
      "name": "Antigravity",
      "nameZh": "Antigravity",
      "icon": "gemini",
      "color": "#4285f4"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".gemini/antigravity"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".gemini/antigravity-ide"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".gemini/antigravity-backup"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".gemini/antigravity-cli/conversations"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Antigravity"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "Antigravity"
        }
      ]
    },
    "storage": {
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".gemini/antigravity/skills"
          },
          {
            "base": "home",
            "path": ".gemini/antigravity-ide/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "antigravity-transcript-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".gemini/antigravity",
            "glob": "**/.system_generated/logs/transcript.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".gemini/antigravity-ide",
            "glob": "**/.system_generated/logs/transcript.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".gemini/antigravity-cli",
            "glob": "**/.system_generated/logs/transcript.jsonl",
            "format": "jsonl"
          }
        ],
        "maxFileSizeBytes": 67108864
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model",
      "tokenSemantics": {
        "reasoningIncludedInOutput": false
      }
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "pi",
    "display": {
      "name": "pi",
      "nameZh": "pi",
      "icon": "other",
      "color": "#fe2857"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".pi"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".pi/agent/sessions"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "craft",
    "display": {
      "name": "Craft Agents",
      "nameZh": "Craft Agents",
      "icon": "other",
      "color": "#f97316"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".craft-agent"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "roo-code",
    "display": {
      "name": "Roo Code",
      "nameZh": "Roo Code",
      "icon": "other",
      "color": "#f0524d"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Code/User/globalStorage/rooveterinaryinc.roo-cline"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "Code/User/globalStorage/rooveterinaryinc.roo-cline/tasks",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "configHome",
            "path": "Code/User/globalStorage/rooveterinaryinc.roo-cline/tasks",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "Code/User/globalStorage/rooveterinaryinc.roo-cline/tasks",
            "glob": "**/*.json",
            "format": "json"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "zed",
    "display": {
      "name": "Zed Agent",
      "nameZh": "Zed Agent",
      "icon": "other",
      "color": "#3b82f6"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Zed"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "zed"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "userProfile",
          "path": "Local/Zed/threads"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "goose",
    "display": {
      "name": "Goose",
      "nameZh": "Goose",
      "icon": "other",
      "color": "#22c55e"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "goose"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".goose"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "droid",
    "display": {
      "name": "Droid",
      "nameZh": "Droid",
      "icon": "other",
      "color": "#1f6feb"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".factory"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "mimo",
    "display": {
      "name": "Mimo Code",
      "nameZh": "Mimo Code",
      "icon": "other",
      "color": "#ff6900"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "dataHome",
          "path": "mimocode"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "orca/mimocode-hooks/shared/data"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "zcode",
    "display": {
      "name": "ZCode",
      "nameZh": "ZCode",
      "icon": "other",
      "color": "#10b981"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".zcode"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".zcode/projects"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".zcode/cli/db/db.sqlite"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "anythingllm",
    "display": {
      "name": "AnythingLLM Desktop",
      "nameZh": "AnythingLLM Desktop",
      "icon": "other",
      "color": "#8b5cf6"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "anythingllm-desktop"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "AnythingLLM"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "configHome",
          "path": "anythingllm"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "dsh",
    "display": {
      "name": "DeepSeek Harness",
      "nameZh": "DeepSeek Harness",
      "icon": "deepseek",
      "color": "#4d6bfe"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".dsh"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "native",
        "reader": "dsh-session-v1",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".dsh/sessions",
            "glob": "**/session.jsonl.zstd",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".dsh/sessions",
            "glob": "**/session.jsonl",
            "format": "jsonl"
          }
        ],
        "maxFileSizeBytes": 67108864
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "resume",
        "reader": "dsh-session-v1",
        "command": [
          "dsh",
          "--profile",
          "tui",
          "--resume",
          "{sessionId}"
        ]
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model",
      "tokenSemantics": {
        "reasoningIncludedInOutput": false
      }
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "aipy",
    "display": {
      "name": "AiPy",
      "nameZh": "AiPy",
      "icon": "other",
      "color": "#14b8a6"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11"
          ],
          "base": "home",
          "path": ".aipyapp"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "aipy-pro"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "aipy-pro"
        }
      ]
    },
    "storage": {
      "dataRoots": [
        {
          "base": "appData",
          "path": "aipy-pro"
        },
        {
          "base": "appDataRoaming",
          "path": "aipy-pro"
        }
      ],
      "skills": {
        "rootSpecs": [
          {
            "base": "home",
            "path": ".aipyapp/skills"
          }
        ],
        "markers": [
          "SKILL.md",
          "skill.md"
        ],
        "maxDepth": 3
      }
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-sqlite",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "aipy-pro",
            "glob": "aipy",
            "format": "sqlite"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "aipy-pro",
            "glob": "aipy",
            "format": "sqlite"
          }
        ],
        "mapping": {
          "timestamp": [
            "timestamp"
          ],
          "sessionId": [
            "sessionId"
          ],
          "model": [
            "model"
          ],
          "project": [
            "project"
          ],
          "inputTokens": [
            "inputTokens"
          ],
          "outputTokens": [
            "outputTokens"
          ],
          "reasoningOutputTokens": [
            "reasoningOutputTokens"
          ],
          "totalTokens": [
            "totalTokens"
          ]
        },
        "maxFileSizeBytes": 536870912,
        "query": "SELECT\n  e.time AS timestamp,\n  e.task_id AS sessionId,\n  COALESCE(NULLIF(e.model, ''), NULLIF(t.model, ''), 'unknown') AS model,\n  COALESCE(\n    NULLIF(w.workdir, ''),\n    CASE\n      WHEN NULLIF(t.title, '') IS NOT NULL THEN\n        COALESCE(\n          CASE\n            WHEN instr(t.workdir, '/aipywork/') > 0 THEN\n              substr(t.workdir, instr(t.workdir, '/aipywork/') + length('/aipywork/'))\n          END,\n          NULLIF(t.id, ''),\n          'unknown'\n        ) || ' - ' || t.title\n    END,\n    NULLIF(t.workdir, ''),\n    'unknown'\n  ) AS project,\n  CAST(COALESCE(json_extract(e.usage, '$.input_tokens'), 0) AS INTEGER) AS inputTokens,\n  CAST(COALESCE(json_extract(e.usage, '$.output_tokens'), 0) AS INTEGER) AS outputTokens,\n  CAST(COALESCE(json_extract(e.usage, '$.reasoning_tokens'), 0) AS INTEGER) AS reasoningOutputTokens,\n  CAST(COALESCE(json_extract(e.usage, '$.total_tokens'), 0) AS INTEGER) AS totalTokens\nFROM task_event e\nLEFT JOIN task t ON t.id = e.task_id\nLEFT JOIN workspace w ON w.id = t.workspace_id\nWHERE e.usage IS NOT NULL AND e.usage <> ''"
      },
      "skills": "read-write",
      "agents": "unsupported",
      "sessions": {
        "mode": "read",
        "reader": "aipy-session-v1"
      },
      "market": "install-target",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "cline",
    "display": {
      "name": "Cline",
      "nameZh": "Cline",
      "icon": "other",
      "color": "#5b8def"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "Code/User/globalStorage/saoudrizwan.claude-dev"
        },
        {
          "targets": [
            "macos",
            "linux"
          ],
          "base": "configHome",
          "path": "Code/User/globalStorage/saoudrizwan.claude-dev"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "Code/User/globalStorage/saoudrizwan.claude-dev"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".cline/data/sessions"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".vscode-server/data/User/globalStorage/saoudrizwan.claude-dev/tasks"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-json",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "Code/User/globalStorage/saoudrizwan.claude-dev/tasks",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "macos",
              "linux"
            ],
            "base": "configHome",
            "path": "Code/User/globalStorage/saoudrizwan.claude-dev/tasks",
            "glob": "**/*.json",
            "format": "json"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "Code/User/globalStorage/saoudrizwan.claude-dev/tasks",
            "glob": "**/*.json",
            "format": "json"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "qwen",
    "display": {
      "name": "Qwen CLI",
      "nameZh": "Qwen CLI",
      "icon": "other",
      "color": "#615ced"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".qwen/projects"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-jsonl",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".qwen/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "commandcode",
    "display": {
      "name": "Command Code",
      "nameZh": "Command Code",
      "icon": "other",
      "color": "#8b5cf6"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".commandcode/projects"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-jsonl",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".commandcode/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "proma",
    "display": {
      "name": "Proma",
      "nameZh": "Proma",
      "icon": "other",
      "color": "#f97316"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".proma/agent-sessions"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-jsonl",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".proma/agent-sessions",
            "glob": "*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "qodercn",
    "display": {
      "name": "Qoder CN",
      "nameZh": "Qoder CN",
      "icon": "other",
      "color": "#22c55e"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "QoderCN/SharedClientCache/cache/db/local.db"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "QoderCN/SharedClientCache/cache/db/local.db"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "configHome",
          "path": "QoderCN/SharedClientCache/cache/db/local.db"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "unsupported"
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "reasonix",
    "display": {
      "name": "Reasonix",
      "nameZh": "Reasonix",
      "icon": "other",
      "color": "#06b6d4"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".reasonix"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".reasonix/stats"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".reasonix/sessions"
        },
        {
          "targets": [
            "macos",
            "windows10",
            "windows11",
            "linux"
          ],
          "base": "home",
          "path": ".reasonix/projects"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-jsonl",
        "paths": [
          {
            "targets": [
              "macos",
              "windows10",
              "windows11",
              "linux"
            ],
            "base": "home",
            "path": ".reasonix/sessions",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  },
  {
    "$schema": "../tool-definition.schema.json",
    "configVersion": 1,
    "id": "cherrystudio",
    "display": {
      "name": "Cherry Studio",
      "nameZh": "Cherry Studio",
      "icon": "other",
      "color": "#ec4899"
    },
    "platforms": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    },
    "detection": {
      "locations": [
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "CherryStudio/Data/Agents/.claude/projects"
        },
        {
          "targets": [
            "macos"
          ],
          "base": "appData",
          "path": "CherryStudio/.claude/projects"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "CherryStudio/Data/Agents/.claude/projects"
        },
        {
          "targets": [
            "windows10",
            "windows11"
          ],
          "base": "appDataRoaming",
          "path": "CherryStudio/.claude/projects"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "configHome",
          "path": "CherryStudio/Data/Agents/.claude/projects"
        },
        {
          "targets": [
            "linux"
          ],
          "base": "configHome",
          "path": "CherryStudio/.claude/projects"
        }
      ]
    },
    "capabilities": {
      "usage": {
        "mode": "adapter",
        "reader": "generic-jsonl",
        "paths": [
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "CherryStudio/Data/Agents/.claude/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "macos"
            ],
            "base": "appData",
            "path": "CherryStudio/.claude/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "CherryStudio/Data/Agents/.claude/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "windows10",
              "windows11"
            ],
            "base": "appDataRoaming",
            "path": "CherryStudio/.claude/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "linux"
            ],
            "base": "configHome",
            "path": "CherryStudio/Data/Agents/.claude/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          },
          {
            "targets": [
              "linux"
            ],
            "base": "configHome",
            "path": "CherryStudio/.claude/projects",
            "glob": "**/*.jsonl",
            "format": "jsonl"
          }
        ]
      },
      "skills": "unsupported",
      "agents": "unsupported",
      "sessions": {
        "mode": "unsupported"
      },
      "market": "unsupported",
      "security": "unsupported"
    },
    "modelObservation": {
      "modelField": "model"
    }
  }
];

export const SHARED_POLICY_PACKS: SharedPolicyPacks = {
  "platformProfiles": {
    "schemaVersion": 1,
    "description": "Per-platform path bases and availability defaults (docs §6.1). Resolution priority: shared default < platform group < platform target < tool definition.",
    "targets": [
      "macos",
      "windows10",
      "windows11",
      "linux"
    ],
    "groups": {
      "windows": [
        "windows10",
        "windows11"
      ]
    },
    "basePlatforms": {
      "home": [
        "macos",
        "windows10",
        "windows11",
        "linux"
      ],
      "userProfile": [
        "windows10",
        "windows11"
      ],
      "appData": [
        "macos"
      ],
      "appDataRoaming": [
        "windows10",
        "windows11"
      ],
      "configHome": [
        "macos",
        "linux"
      ],
      "dataHome": [
        "macos",
        "linux"
      ]
    },
    "xdgFallback": {
      "configHome": "~/.config",
      "dataHome": "~/.local/share"
    },
    "defaultStatus": {
      "macos": "supported",
      "windows": "supported",
      "linux": "planned"
    }
  },
  "genericReaderDefaults": {
    "schemaVersion": 1,
    "description": "Default field candidates + size cap for generic readers (moved from COMMON_MAPPING / GENERIC_ADAPTER_MAX_FILE_SIZE_BYTES in local-usage/adapters/catalog.ts).",
    "defaultMapping": {
      "records": [
        "events",
        "messages",
        "turns",
        "history",
        "items",
        "data.events",
        "data.messages"
      ],
      "timestamp": [
        "timestamp",
        "created_at",
        "createdAt",
        "time",
        "metadata.timestamp",
        "usage.timestamp"
      ],
      "sessionId": [
        "session_id",
        "sessionId",
        "conversation_id",
        "conversationId",
        "thread_id",
        "threadId",
        "message.session_id",
        "message.sessionId",
        "metadata.session_id",
        "metadata.sessionId"
      ],
      "model": [
        "model",
        "model_id",
        "modelId",
        "metadata.model",
        "usage.model"
      ],
      "project": [
        "cwd",
        "project",
        "project_path",
        "projectPath",
        "workspace",
        "workspace_path",
        "metadata.cwd"
      ],
      "inputTokens": [
        "usage.input_tokens",
        "usage.inputTokens",
        "token_usage.input_tokens",
        "tokenUsage.inputTokens",
        "tokens.input",
        "metrics.input_tokens"
      ],
      "cachedInputTokens": [
        "usage.cached_input_tokens",
        "usage.cache_read_input_tokens",
        "usage.cachedInputTokens",
        "token_usage.cached_input_tokens",
        "tokenUsage.cachedInputTokens",
        "tokens.cached_input"
      ],
      "cacheCreationInputTokens": [
        "usage.cache_creation_input_tokens",
        "usage.cacheCreationInputTokens",
        "token_usage.cache_creation_input_tokens",
        "tokens.cache_creation_input"
      ],
      "outputTokens": [
        "usage.output_tokens",
        "usage.outputTokens",
        "token_usage.output_tokens",
        "tokenUsage.outputTokens",
        "tokens.output",
        "metrics.output_tokens"
      ],
      "reasoningOutputTokens": [
        "usage.reasoning_output_tokens",
        "usage.reasoningOutputTokens",
        "token_usage.reasoning_output_tokens",
        "tokens.reasoning"
      ],
      "totalTokens": [
        "usage.total_tokens",
        "usage.totalTokens",
        "token_usage.total_tokens",
        "tokenUsage.totalTokens",
        "tokens.total",
        "metrics.total_tokens"
      ]
    },
    "defaultMaxFileSizeBytes": 8388608
  },
  "scannerPolicy": {
    "schemaVersion": 1,
    "description": "Scanner budgets and cache naming policy (moved from local-usage/scanner.server.ts constants). Execution (walking, I/O, cache versioning) stays in TypeScript.",
    "lookbackDays": 3650,
    "maxFilesPerSource": 1200,
    "maxDiscoveredEntriesPerSource": 30000,
    "maxJsonlLineLength": 16777216,
    "futureTimestampToleranceMs": 86400000,
    "cacheNote": "The implementation cache version (PERSISTENT_CACHE_VERSION) and the registry fingerprint stay in TypeScript; changing either invalidates the persistent cache."
  },
  "skillMarketPolicy": {
    "schemaVersion": 1,
    "description": "Skill-agent UI order, default discovery settings and market install conditions (moved from SKILL_AGENT_ORDER / DEFAULT_MARKERS in local-skills/agent-rules.ts).",
    "skillAgentOrder": [
      "claude-code",
      "codex",
      "cursor",
      "gemini-cli",
      "opencode",
      "grok",
      "hermes",
      "openclaw",
      "antigravity",
      "aipy"
    ],
    "defaultMarkers": [
      "SKILL.md",
      "skill.md"
    ],
    "defaultMaxDepth": 3,
    "marketInstallCondition": {
      "requires": [
        "skills.mode=read-write",
        "storage.skills.rootSpecs"
      ],
      "note": "A tool without skill roots must not auto-become a market install target (docs §6)."
    }
  },
  "usageTaxonomy": {
    "schemaVersion": 1,
    "description": "Behavior classification hints and context dimensions (moved from DEBUG_COMMAND_HINTS in local-usage/behavior-classify.ts). Display labels live in the i18n dictionaries.",
    "debugCommandHints": [
      "diff",
      "grep",
      "log",
      "status",
      "test",
      "lint"
    ],
    "behaviorPriority": [
      "debug-command",
      "execution",
      "browser",
      "agent",
      "planning",
      "text-qa"
    ],
    "contextDimensions": {
      "tools": {
        "i18nKey": "dashboard.context.dimTool"
      },
      "skills": {
        "i18nKey": "dashboard.context.dimSkill"
      },
      "commands": {
        "i18nKey": "dashboard.context.dimMessages"
      },
      "mcp": {
        "i18nKey": "dashboard.context.dimMcp"
      },
      "toolOutputs": {
        "i18nKey": "dashboard.context.dimTool"
      }
    }
  },
  "definitionsManifest": {
    "schemaVersion": 1,
    "description": "Explicit, ordered list of built-in tool definitions (docs §5: fixed import list, no runtime directory scanning). Order matches the frozen baseline UI order; aipy/cline are legacy sources (catalogVisible=false).",
    "tools": [
      {
        "id": "claude-code",
        "path": "claude-code.tool.json"
      },
      {
        "id": "codex",
        "path": "codex.tool.json"
      },
      {
        "id": "cursor",
        "path": "cursor.tool.json"
      },
      {
        "id": "kiro",
        "path": "kiro.tool.json"
      },
      {
        "id": "gemini-cli",
        "path": "gemini-cli.tool.json"
      },
      {
        "id": "opencode",
        "path": "opencode.tool.json"
      },
      {
        "id": "openclaw",
        "path": "openclaw.tool.json"
      },
      {
        "id": "every-code",
        "path": "every-code.tool.json"
      },
      {
        "id": "hermes",
        "path": "hermes.tool.json"
      },
      {
        "id": "github-copilot",
        "path": "github-copilot.tool.json"
      },
      {
        "id": "kimi-code",
        "path": "kimi-code.tool.json"
      },
      {
        "id": "omp",
        "path": "omp.tool.json"
      },
      {
        "id": "codebuddy",
        "path": "codebuddy.tool.json"
      },
      {
        "id": "workbuddy",
        "path": "workbuddy.tool.json"
      },
      {
        "id": "grok",
        "path": "grok.tool.json"
      },
      {
        "id": "kilo-cli",
        "path": "kilo-cli.tool.json"
      },
      {
        "id": "kilocode",
        "path": "kilocode.tool.json"
      },
      {
        "id": "antigravity",
        "path": "antigravity.tool.json"
      },
      {
        "id": "pi",
        "path": "pi.tool.json"
      },
      {
        "id": "craft",
        "path": "craft.tool.json"
      },
      {
        "id": "roo-code",
        "path": "roo-code.tool.json"
      },
      {
        "id": "zed",
        "path": "zed.tool.json"
      },
      {
        "id": "goose",
        "path": "goose.tool.json"
      },
      {
        "id": "droid",
        "path": "droid.tool.json"
      },
      {
        "id": "mimo",
        "path": "mimo.tool.json"
      },
      {
        "id": "zcode",
        "path": "zcode.tool.json"
      },
      {
        "id": "anythingllm",
        "path": "anythingllm.tool.json"
      },
      {
        "id": "dsh",
        "path": "dsh.tool.json"
      },
      {
        "id": "aipy",
        "path": "aipy.tool.json"
      },
      {
        "id": "cline",
        "path": "cline.tool.json"
      },
      {
        "id": "qwen",
        "path": "qwen.tool.json"
      },
      {
        "id": "commandcode",
        "path": "commandcode.tool.json"
      },
      {
        "id": "proma",
        "path": "proma.tool.json"
      },
      {
        "id": "qodercn",
        "path": "qodercn.tool.json"
      },
      {
        "id": "reasonix",
        "path": "reasonix.tool.json"
      },
      {
        "id": "cherrystudio",
        "path": "cherrystudio.tool.json"
      }
    ]
  }
};

export const TOOL_REGISTRY_VERSION: string = "1875799686af094d";
