// @generated by scripts/generate-tool-manifest.mjs — DO NOT EDIT.
import type { PublicToolManifest } from "./manifest.ts";

export const PUBLIC_TOOL_MANIFEST: PublicToolManifest = {
  "configVersion": 1,
  "tools": [
    {
      "id": "claude-code",
      "name": "Claude Code",
      "nameZh": "Claude Code",
      "capabilities": {
        "usage": "native",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "resume",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "codex",
      "name": "Codex CLI",
      "nameZh": "Codex CLI",
      "capabilities": {
        "usage": "native",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "resume",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "cursor",
      "name": "Cursor",
      "nameZh": "Cursor",
      "capabilities": {
        "usage": "adapter",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "kiro",
      "name": "Kiro",
      "nameZh": "Kiro",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "gemini-cli",
      "name": "Gemini CLI",
      "nameZh": "Gemini CLI",
      "capabilities": {
        "usage": "adapter",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "opencode",
      "name": "OpenCode",
      "nameZh": "OpenCode",
      "capabilities": {
        "usage": "adapter",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "openclaw",
      "name": "OpenClaw",
      "nameZh": "OpenClaw",
      "capabilities": {
        "usage": "unsupported",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "every-code",
      "name": "Every Code",
      "nameZh": "Every Code",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "hermes",
      "name": "Hermes Agent",
      "nameZh": "Hermes Agent",
      "capabilities": {
        "usage": "unsupported",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "github-copilot",
      "name": "GitHub Copilot",
      "nameZh": "GitHub Copilot",
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "kimi-code",
      "name": "Kimi Code",
      "nameZh": "Kimi Code",
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "omp",
      "name": "oh-my-pi",
      "nameZh": "oh-my-pi",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "codebuddy",
      "name": "CodeBuddy",
      "nameZh": "CodeBuddy",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "workbuddy",
      "name": "WorkBuddy",
      "nameZh": "WorkBuddy",
      "capabilities": {
        "usage": "native",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "grok",
      "name": "Grok Build",
      "nameZh": "Grok Build",
      "capabilities": {
        "usage": "adapter",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "resume",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "kilo-cli",
      "name": "Kilo CLI",
      "nameZh": "Kilo CLI",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "kilocode",
      "name": "Kilo Code",
      "nameZh": "Kilo Code",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "antigravity",
      "name": "Antigravity",
      "nameZh": "Antigravity",
      "capabilities": {
        "usage": "unsupported",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "pi",
      "name": "pi",
      "nameZh": "pi",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "craft",
      "name": "Craft Agents",
      "nameZh": "Craft Agents",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "roo-code",
      "name": "Roo Code",
      "nameZh": "Roo Code",
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "zed",
      "name": "Zed Agent",
      "nameZh": "Zed Agent",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "goose",
      "name": "Goose",
      "nameZh": "Goose",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "droid",
      "name": "Droid",
      "nameZh": "Droid",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "mimo",
      "name": "Mimo Code",
      "nameZh": "Mimo Code",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "zcode",
      "name": "ZCode",
      "nameZh": "ZCode",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "anythingllm",
      "name": "AnythingLLM Desktop",
      "nameZh": "AnythingLLM Desktop",
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    }
  ]
};
