// @generated by scripts/generate-tool-manifest.mjs — DO NOT EDIT.
import type { PublicToolManifest } from "./manifest.ts";

export const PUBLIC_TOOL_MANIFEST: PublicToolManifest = {
  "configVersion": 1,
  "tools": [
    {
      "id": "claude-code",
      "name": "Claude Code",
      "nameZh": "Claude Code",
      "icon": "claude",
      "color": "#d97757",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "native",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "resume",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "codex",
      "name": "Codex",
      "nameZh": "Codex",
      "icon": "https://chatgpt.com/cdn/assets/favicon-l4nq08hd.svg",
      "color": "#10a37f",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "native",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "resume",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "cursor",
      "name": "Cursor",
      "nameZh": "Cursor",
      "icon": "cursor",
      "color": "#cfcfcf",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "kiro",
      "name": "Kiro",
      "nameZh": "Kiro",
      "icon": "https://kiro.dev/icon.svg?fe599162bb293ea0",
      "color": "#01a4ff",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "gemini-cli",
      "name": "Gemini CLI",
      "nameZh": "Gemini CLI",
      "icon": "https://geminicli.com/favicon.ico",
      "color": "#4285f4",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "native",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "opencode",
      "name": "OpenCode",
      "nameZh": "OpenCode",
      "icon": "https://opencode.ai/favicon-v3.ico",
      "color": "#f59e0b",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "openclaw",
      "name": "OpenClaw",
      "nameZh": "OpenClaw",
      "icon": "other",
      "color": "#ff5543",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "native",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "every-code",
      "name": "Every Code",
      "nameZh": "Every Code",
      "icon": "https://justevery.com/img/favicon.svg",
      "color": "#00c2a8",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "hermes",
      "name": "Hermes Agent",
      "nameZh": "Hermes Agent",
      "icon": "other",
      "color": "#a78bfa",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "github-copilot",
      "name": "GitHub Copilot",
      "nameZh": "GitHub Copilot",
      "icon": "other",
      "color": "#6e7681",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "kimi-code",
      "name": "Kimi Code",
      "nameZh": "Kimi Code",
      "icon": "kimi",
      "color": "#7c5cff",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "omp",
      "name": "oh-my-pi",
      "nameZh": "oh-my-pi",
      "icon": "other",
      "color": "#00b3ff",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "codebuddy",
      "name": "CodeBuddy",
      "nameZh": "CodeBuddy",
      "icon": "other",
      "color": "#0052d9",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "workbuddy",
      "name": "WorkBuddy",
      "nameZh": "WorkBuddy",
      "icon": "https://codebuddy-1328495429.cos.accelerate.myqcloud.com/web/workbuddy/7c350554d6e526d96bb1d2ba32fd594611e9e711/assets/logo.svg",
      "color": "#22d3ee",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "native",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "grok",
      "name": "Grok Build",
      "nameZh": "Grok Build",
      "icon": "other",
      "color": "#d1d5db",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "native",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "resume",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "kilo-cli",
      "name": "Kilo CLI",
      "nameZh": "Kilo CLI",
      "icon": "other",
      "color": "#eab308",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "kilocode",
      "name": "Kilo Code",
      "nameZh": "Kilo Code",
      "icon": "other",
      "color": "#eab308",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "antigravity",
      "name": "Antigravity",
      "nameZh": "Antigravity",
      "icon": "gemini",
      "color": "#4285f4",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "native",
        "skills": "read-write",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "install-target",
        "security": "unsupported"
      }
    },
    {
      "id": "pi",
      "name": "pi",
      "nameZh": "pi",
      "icon": "https://pi.dev/favicon.svg",
      "color": "#fe2857",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "craft",
      "name": "Craft Agents",
      "nameZh": "Craft Agents",
      "icon": "https://agents.craft.do/favicon.ico",
      "color": "#f97316",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "roo-code",
      "name": "Roo Code",
      "nameZh": "Roo Code",
      "icon": "https://roomote.dev/favicon.ico",
      "color": "#f0524d",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "zed",
      "name": "Zed Agent",
      "nameZh": "Zed Agent",
      "icon": "https://zed.dev/favicon_black_32.png",
      "color": "#3b82f6",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "goose",
      "name": "Goose",
      "nameZh": "Goose",
      "icon": "https://goose-docs.ai/img/favicon.ico",
      "color": "#22c55e",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "droid",
      "name": "Droid",
      "nameZh": "Droid",
      "icon": "https://factory.ai/favicon.svg",
      "color": "#1f6feb",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "mimo",
      "name": "Mimo Code",
      "nameZh": "Mimo Code",
      "icon": "https://cdn.cnbj1.fds.api.mi-img.com/aife/mimo-blog-fe/doc_build/mimo.ico",
      "color": "#ff6900",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "zcode",
      "name": "ZCode",
      "nameZh": "ZCode",
      "icon": "other",
      "color": "#10b981",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "anythingllm",
      "name": "AnythingLLM Desktop",
      "nameZh": "AnythingLLM Desktop",
      "icon": "other",
      "color": "#8b5cf6",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "dsh",
      "name": "DeepSeek Harness",
      "nameZh": "DeepSeek Harness",
      "icon": "deepseek",
      "color": "#4d6bfe",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "native",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "resume",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "aipy",
      "name": "AiPy",
      "nameZh": "AiPy",
      "icon": "https://www.aipyaipy.com/image/logo.webp",
      "color": "#14b8a6",
      "legacy": true,
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "cline",
      "name": "Cline",
      "nameZh": "Cline",
      "icon": "https://cline.bot/assets/branding/favicons/favicon-32x32.png",
      "color": "#5b8def",
      "legacy": true,
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "qwen",
      "name": "Qwen CLI",
      "nameZh": "Qwen CLI",
      "icon": "https://img.alicdn.com/imgextra/i4/O1CN01OXv3EM1FN8t9W4P79_!!6000000000474-2-tps-80-80.png",
      "color": "#615ced",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "commandcode",
      "name": "Command Code",
      "nameZh": "Command Code",
      "icon": "https://commandcode.ai/favicon.ico",
      "color": "#8b5cf6",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "proma",
      "name": "Proma",
      "nameZh": "Proma",
      "icon": "https://proma.cool/favicon.png",
      "color": "#f97316",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "qodercn",
      "name": "Qoder CN",
      "nameZh": "Qoder CN",
      "icon": "https://img.alicdn.com/imgextra/i3/O1CN01KliT1u1jEq947NlKH_!!6000000004517-55-tps-180-180.svg",
      "color": "#22c55e",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "unsupported",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "reasonix",
      "name": "Reasonix",
      "nameZh": "Reasonix",
      "icon": "other",
      "color": "#06b6d4",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    },
    {
      "id": "cherrystudio",
      "name": "Cherry Studio",
      "nameZh": "Cherry Studio",
      "icon": "https://www.cherryai.com/assets/logo-Bz2G6ABc.png",
      "color": "#ec4899",
      "platforms": {
        "macos": "supported",
        "windows10": "supported",
        "windows11": "supported",
        "linux": "planned"
      },
      "capabilities": {
        "usage": "adapter",
        "skills": "unsupported",
        "agents": "unsupported",
        "sessions": "unsupported",
        "market": "unsupported",
        "security": "unsupported"
      }
    }
  ],
  "skillAgentOrder": [
    "claude-code",
    "codex",
    "cursor",
    "gemini-cli",
    "opencode",
    "grok",
    "hermes",
    "openclaw",
    "antigravity"
  ]
};
