import type { Severity } from "../types.js";

export interface RuleMeta { weight?: number; cweId?: string; fileTypes?: string[]; bypassVerification?: boolean }
/** Default deduction weights (by severity); high-risk rules are weighted individually via RULE_META. */
export const DEFAULT_SEVERITY_WEIGHT: Record<Severity, number> = { critical: 45, high: 35, medium: 20, low: 10 };
export const RULE_META: Record<string, RuleMeta> = {
  "builtin-01": { weight: 45 }, "builtin-03": { weight: 45 }, "builtin-07": { weight: 45 },
  "builtin-12": { weight: 55 }, "builtin-13": { weight: 55 }, "builtin-14": { weight: 45 },
  "builtin-27": { weight: 25, cweId: "CWE-94", fileTypes: ["py"] },
  "builtin-28": { weight: 30, cweId: "CWE-78", fileTypes: ["py"] },
  "builtin-29": { weight: 30, cweId: "CWE-502", fileTypes: ["py"] },
  "builtin-30": { weight: 30, cweId: "CWE-78", fileTypes: ["js", "ts", "jsx", "tsx"] },
  "builtin-31": { weight: 45, cweId: "CWE-78", fileTypes: ["php"] },
  "builtin-32": { weight: 25, cweId: "CWE-78", fileTypes: ["rb"] },
  "builtin-33": { weight: 25, cweId: "CWE-78", fileTypes: ["go", "java", "cs"] },
  "builtin-34": { weight: 45, cweId: "CWE-506" },
  "builtin-35": { weight: 30, cweId: "CWE-78" },
  "builtin-36": { weight: 25, cweId: "CWE-78" },
  "builtin-37": { weight: 30, cweId: "CWE-506" },
  "builtin-38": { weight: 30, cweId: "CWE-506" },
  "builtin-39": { weight: 25, cweId: "CWE-506" },
  "builtin-40": { weight: 45, cweId: "CWE-78" },
  "builtin-41": { weight: 30, cweId: "CWE-798" },
  "builtin-42": { weight: 35, cweId: "CWE-798" },
  "builtin-43": { weight: 45, cweId: "CWE-522" },
  "builtin-44": { weight: 25, cweId: "CWE-522" },
  "builtin-45": { weight: 55, cweId: "CWE-918", bypassVerification: true },
  "builtin-46": { weight: 50, cweId: "CWE-319", bypassVerification: true },
  "builtin-47": { weight: 55, cweId: "CWE-829", bypassVerification: true },
  "builtin-48": { weight: 55, cweId: "CWE-829", bypassVerification: true },
  "builtin-49": { weight: 55, cweId: "CWE-494", bypassVerification: true },
  "builtin-50": { weight: 20, cweId: "CWE-506" },
  "builtin-51": { weight: 25, cweId: "CWE-506" },
  "builtin-52": { weight: 20, cweId: "CWE-177" },
  "builtin-53": { weight: 10, cweId: "CWE-506" },
  "builtin-54": { weight: 35, cweId: "CWE-319" },
  "builtin-55": { weight: 10, cweId: "CWE-319" },
  "builtin-56": { weight: 10, cweId: "CWE-319" },
  "builtin-57": { weight: 15, cweId: "CWE-319", fileTypes: ["js", "jsx", "ts", "tsx"] },
  "builtin-58": { weight: 45, cweId: "CWE-522" },
  "builtin-59": { weight: 45, cweId: "CWE-522" },
  "builtin-60": { weight: 55, cweId: "CWE-78", bypassVerification: true },
  "builtin-61": { weight: 55, cweId: "CWE-829", bypassVerification: true },
};
