/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as DistillRouteImport } from './routes/distill'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/agents.lazy').then((d) => d.Route))
const DistillRoute = DistillRouteImport.update({
  id: '/distill',
  path: '/distill',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/distill.lazy').then((d) => d.Route))
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/market.lazy').then((d) => d.Route))
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/memory.lazy').then((d) => d.Route))
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reports.lazy').then((d) => d.Route))
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/security.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/skills.lazy').then((d) => d.Route))
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sources.lazy').then((d) => d.Route))
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tracker.lazy').then((d) => d.Route))
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/widget.lazy').then((d) => d.Route))
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chats.index.lazy').then((d) => d.Route))
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chats.$id.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/distill': typeof DistillRoute
  '/market': typeof MarketRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/sources': typeof SourcesRoute
  '/tracker': typeof TrackerRoute
  '/widget': typeof WidgetRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/distill': typeof DistillRoute
  '/market': typeof MarketRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/sources': typeof SourcesRoute
  '/tracker': typeof TrackerRoute
  '/widget': typeof WidgetRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats': typeof ChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/distill': typeof DistillRoute
  '/market': typeof MarketRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/sources': typeof SourcesRoute
  '/tracker': typeof TrackerRoute
  '/widget': typeof WidgetRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/distill'
    | '/market'
    | '/memory'
    | '/reports'
    | '/security'
    | '/settings'
    | '/skills'
    | '/sources'
    | '/tracker'
    | '/widget'
    | '/chats/$id'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/distill'
    | '/market'
    | '/memory'
    | '/reports'
    | '/security'
    | '/settings'
    | '/skills'
    | '/sources'
    | '/tracker'
    | '/widget'
    | '/chats/$id'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/distill'
    | '/market'
    | '/memory'
    | '/reports'
    | '/security'
    | '/settings'
    | '/skills'
    | '/sources'
    | '/tracker'
    | '/widget'
    | '/chats/$id'
    | '/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  DistillRoute: typeof DistillRoute
  MarketRoute: typeof MarketRoute
  MemoryRoute: typeof MemoryRoute
  ReportsRoute: typeof ReportsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SourcesRoute: typeof SourcesRoute
  TrackerRoute: typeof TrackerRoute
  WidgetRoute: typeof WidgetRoute
  ChatsIdRoute: typeof ChatsIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distill': {
      id: '/distill'
      path: '/distill'
      fullPath: '/distill'
      preLoaderRoute: typeof DistillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  DistillRoute: DistillRoute,
  MarketRoute: MarketRoute,
  MemoryRoute: MemoryRoute,
  ReportsRoute: ReportsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SourcesRoute: SourcesRoute,
  TrackerRoute: TrackerRoute,
  WidgetRoute: WidgetRoute,
  ChatsIdRoute: ChatsIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
