import type { InsightSurfaceId } from "./contracts.ts";

/**
 * The authoritative list of rule fact ids per surface. A candidate's `factKey`
 * is the template literal `insights.page.${surface}.${id}` — adaptors reference
 * this map so id drift and missing translations fail compilation, not runtime.
 */
export const PAGE_RULE_IDS: Record<InsightSurfaceId, readonly string[]> = {
  dashboard: [
    "dashboard-watch",
    "dashboard-assets",
    "dashboard-usage",
    "dashboard-security-safe",
    "dashboard-security-risk",
    "dashboard-efficiency",
    "dashboard-empty",
    "dashboard-guide-collection",
    "dashboard-guide-sessions",
    "dashboard-guide-concentration",
    "dashboard-guide-cache",
    "dashboard-guide-distill",
  ],
  agents: [
    "agents-overview",
    "agents-focus-prompt",
    "agents-focus-cache",
    "agents-focus-security",
    "agents-prompt-guide",
    "agents-guide-coverage",
    "agents-guide-activity",
    "agents-guide-prompt",
    "agents-guide-cache",
    "agents-guide-security",
  ],
  distill: [
    "distill-ready",
    "distill-pending",
    "distill-quota",
    "distill-empty",
    "distill-focus",
    "distill-repeat",
    "distill-guide-intake",
    "distill-guide-outputs",
    "distill-guide-quota",
    "distill-guide-reuse",
    "distill-guide-start",
  ],
  reports: [
    "reports-highlights",
    "reports-security",
    "reports-latest",
    "reports-empty",
    "reports-collab",
    "reports-next",
    "reports-guide-inventory",
    "reports-guide-highlights",
    "reports-guide-security",
    "reports-guide-workflow",
    "reports-guide-next",
  ],
  memory: [
    "memory-total",
    "memory-auto",
    "memory-empty",
    "memory-kinds",
    "memory-guide-inventory",
    "memory-guide-approval",
    "memory-guide-hygiene",
    "memory-guide-types",
    "memory-guide-distill",
  ],
  security: [
    "security-risk-top",
    "security-scan-gap",
    "security-scan-coverage",
    "security-last-scan",
    "security-scan-first",
    "security-history",
    "security-guide-posture",
    "security-guide-failures",
    "security-guide-coverage",
    "security-guide-recency",
    "security-guide-scan",
  ],
  tracker: [
    "tracker-burn-leader",
    "tracker-waste-leader",
    "tracker-cache-low",
    "tracker-suggest",
    "tracker-top-model",
    "tracker-top-project",
    "tracker-empty",
    "tracker-guide-consumption",
    "tracker-guide-waste",
    "tracker-guide-cache",
    "tracker-guide-concentration",
    "tracker-guide-optimize",
  ],
  skills: [
    "skills-local",
    "skills-enabled",
    "skills-unscanned",
    "skills-sync",
    "skills-specific",
    "skills-guide-inventory",
    "skills-guide-enablement",
    "skills-guide-coverage",
    "skills-guide-updates",
    "skills-guide-safety",
  ],
  market: [
    "market-installed",
    "market-updates",
    "market-scan-first",
    "market-review",
    "market-guide-installs",
    "market-guide-updates",
    "market-guide-cache",
    "market-guide-review",
    "market-guide-install",
  ],
  chats: [
    "chats-total",
    "chats-top-source",
    "chats-recoverable",
    "chats-empty",
    "chats-resume",
    "chats-distill",
    "chats-guide-inventory",
    "chats-guide-sources",
    "chats-guide-recovery",
    "chats-guide-activity",
    "chats-guide-distill",
  ],
  "chat-detail": [
    "chat-detail-turns",
    "chat-detail-tokens",
    "chat-detail-recoverable",
    "chat-detail-resume",
    "chat-detail-guide-turns",
    "chat-detail-guide-tokens",
    "chat-detail-guide-state",
    "chat-detail-guide-recovery",
    "chat-detail-guide-distill",
  ],
  widget: [
    "widget-broadcast-security",
    "widget-broadcast-efficiency",
    "widget-broadcast-distill",
  ],
  settings: [
    "settings-model-unconfigured",
    "settings-scan-plan",
    "settings-collection",
    "settings-local",
    "settings-guide-model",
    "settings-guide-enhancement",
    "settings-guide-schedules",
    "settings-guide-retention",
    "settings-guide-privacy",
  ],
  sources: [
    "sources-connected",
    "sources-malformed",
    "sources-not-installed",
    "sources-all-good",
    "sources-rescan",
    "sources-local",
    "sources-guide-inventory",
    "sources-guide-availability",
    "sources-guide-logs",
    "sources-guide-rescan",
    "sources-guide-privacy",
  ],
};
